import { Question } from '../types';

export const seedQuestions: Question[] = [
    // ===== TRANSTORNOS DO HUMOR =====
    {
        id: 'th001',
        theme: 'transtornos_humor',
        difficulty: 2,
        statement: 'Paciente feminina, 35 anos, apresenta humor deprimido há 3 semanas, anedonia, insônia terminal, perda de 4kg, lentificação psicomotora e ideação suicida passiva. Qual o diagnóstico mais provável segundo o DSM-5?',
        options: {
            A: 'Transtorno depressivo persistente (distimia)',
            B: 'Episódio depressivo maior',
            C: 'Transtorno de adaptação com humor deprimido',
            D: 'Transtorno bipolar tipo II, episódio depressivo atual',
            E: 'Transtorno depressivo devido a condição médica',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'O quadro preenche critérios para Episódio Depressivo Maior: humor deprimido e anedonia presentes por mais de 2 semanas, associados a sintomas neurovegetativos (insônia, perda de peso) e ideação suicida.',
            wrongA: 'A distimia requer duração mínima de 2 anos e sintomas menos intensos.',
            wrongC: 'O transtorno de adaptação ocorre em resposta a estressor identificável e não apresenta sintomas tão intensos.',
            wrongD: 'Não há evidência de episódio maníaco ou hipomaníaco prévio.',
            wrongE: 'Não há evidência de condição médica causadora.',
            keyConcepts: ['Critérios DSM-5 para depressão maior', 'Duração mínima de 2 semanas', 'Sintomas cardinais: humor deprimido e anedonia'],
            examTip: 'Na prova, sempre verifique a duração dos sintomas para diferenciar os transtornos depressivos.',
        },
        source: 'DSM-5',
        tags: ['depressão', 'diagnóstico', 'DSM-5'],
    },
    {
        id: 'th002',
        theme: 'transtornos_humor',
        difficulty: 3,
        statement: 'Qual das seguintes características diferencia o Transtorno Bipolar tipo II do tipo I?',
        options: {
            A: 'Presença de episódios depressivos mais graves no tipo II',
            B: 'Ausência de episódios maníacos completos no tipo II',
            C: 'Maior resposta ao lítio no tipo II',
            D: 'Início mais tardio no tipo II',
            E: 'Maior associação com psicose no tipo II',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'O TAB tipo II caracteriza-se pela presença de episódios hipomaníacos (nunca mania completa) e pelo menos um episódio depressivo maior. A mania completa define o TAB tipo I.',
            wrongA: 'Não há evidência de que depressões sejam mais graves no tipo II.',
            wrongC: 'O lítio tem eficácia em ambos os tipos.',
            wrongD: 'O início é semelhante em ambos os tipos.',
            wrongE: 'A psicose é mais comum no tipo I durante mania.',
            keyConcepts: ['Hipomania vs Mania', 'Critérios diagnósticos TAB I e II', 'Duração e intensidade dos episódios'],
            examTip: 'Hipomania: 4 dias; Mania: 7 dias (ou hospitalização). Psicose só ocorre na mania.',
        },
        source: 'Kaplan & Sadock',
        tags: ['bipolar', 'diagnóstico diferencial', 'hipomania'],
    },
    {
        id: 'th003',
        theme: 'transtornos_humor',
        difficulty: 2,
        statement: 'O especificador "com características mistas" em um episódio depressivo maior requer a presença de quantos sintomas maníacos/hipomaníacos?',
        options: {
            A: 'Pelo menos 1',
            B: 'Pelo menos 2',
            C: 'Pelo menos 3',
            D: 'Pelo menos 4',
            E: 'Pelo menos 5',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'Segundo o DSM-5, o especificador "com características mistas" requer pelo menos 3 sintomas maníacos/hipomaníacos presentes durante a maioria dos dias do episódio depressivo.',
            wrongA: 'Um sintoma é insuficiente para o especificador.',
            wrongB: 'Dois sintomas também são insuficientes.',
            wrongD: 'Quatro não é o número mínimo exigido.',
            wrongE: 'Cinco sintomas não são necessários.',
            keyConcepts: ['Especificadores do DSM-5', 'Estados mistos', 'Sobreposição de sintomas'],
            examTip: 'Estados mistos têm pior prognóstico e maior risco de suicídio.',
        },
        source: 'DSM-5',
        tags: ['especificadores', 'estados mistos', 'DSM-5'],
    },
    {
        id: 'th004',
        theme: 'transtornos_humor',
        difficulty: 3,
        statement: 'Paciente com depressão maior grave e sintomas psicóticos. Qual a melhor conduta inicial?',
        options: {
            A: 'Antidepressivo isolado em dose alta',
            B: 'Antipsicótico isolado',
            C: 'Combinação de antidepressivo e antipsicótico',
            D: 'Estabilizador de humor isolado',
            E: 'Benzodiazepínico em dose alta',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'A depressão psicótica responde melhor à combinação de antidepressivo + antipsicótico ou à eletroconvulsoterapia. Monoterapia com antidepressivo é insuficiente.',
            wrongA: 'Antidepressivo isolado tem baixa eficácia na depressão psicótica.',
            wrongB: 'Antipsicótico isolado não trata adequadamente os sintomas depressivos.',
            wrongD: 'Estabilizadores não são primeira linha para depressão unipolar psicótica.',
            wrongE: 'Benzodiazepínicos não tratam depressão ou psicose.',
            keyConcepts: ['Depressão psicótica', 'Tratamento combinado', 'ECT como alternativa'],
            examTip: 'ECT é altamente eficaz na depressão psicótica se medicação falhar.',
        },
        source: 'APA Guidelines',
        tags: ['tratamento', 'depressão psicótica', 'farmacologia'],
    },

    // ===== PSICOFARMACOLOGIA =====
    {
        id: 'pf001',
        theme: 'psicofarmacologia',
        difficulty: 2,
        statement: 'Qual o principal mecanismo de ação dos antidepressivos ISRS?',
        options: {
            A: 'Bloqueio da recaptação de noradrenalina',
            B: 'Inibição da monoaminoxidase',
            C: 'Bloqueio seletivo da recaptação de serotonina',
            D: 'Antagonismo de receptores 5-HT2',
            E: 'Agonismo dopaminérgico direto',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'Os ISRS (Inibidores Seletivos da Recaptação de Serotonina) bloqueiam o transportador de serotonina (SERT), aumentando a disponibilidade de 5-HT na fenda sináptica.',
            wrongA: 'Este é o mecanismo de antidepressivos noradrenérgicos (ex: reboxetina).',
            wrongB: 'Este é o mecanismo dos IMAO.',
            wrongD: 'Este é um mecanismo secundário de alguns antipsicóticos atípicos.',
            wrongE: 'Não há agonismo dopaminérgico direto nos ISRS.',
            keyConcepts: ['SERT', 'Serotonina', 'Mecanismo de ação ISRS'],
            examTip: 'ISRS: seletividade para serotonina. Menos efeitos colaterais que tricíclicos.',
        },
        source: 'Stahl Psychopharmacology',
        tags: ['ISRS', 'mecanismo de ação', 'serotonina'],
    },
    {
        id: 'pf002',
        theme: 'psicofarmacologia',
        difficulty: 3,
        statement: 'Paciente em uso de IMAO. Qual alimento deve ser rigorosamente evitado?',
        options: {
            A: 'Frutas cítricas',
            B: 'Leite integral',
            C: 'Queijos envelhecidos',
            D: 'Pão integral',
            E: 'Arroz branco',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'Queijos envelhecidos contêm tiramina, que ao não ser metabolizada pela MAO inibida, pode causar crise hipertensiva grave (reação do queijo).',
            wrongA: 'Frutas cítricas não contêm quantidades relevantes de tiramina.',
            wrongB: 'Leite não envelhecido não representa risco.',
            wrongD: 'Pão integral não contém tiramina em quantidade perigosa.',
            wrongE: 'Arroz não representa risco.',
            keyConcepts: ['Reação do queijo', 'Tiramina', 'Crise hipertensiva'],
            examTip: 'Outros alimentos ricos em tiramina: vinho tinto, embutidos, fígado.',
        },
        source: 'Stahl Psychopharmacology',
        tags: ['IMAO', 'interações', 'tiramina'],
    },
    {
        id: 'pf003',
        theme: 'psicofarmacologia',
        difficulty: 2,
        statement: 'Qual antipsicótico atípico apresenta maior risco de agranulocitose?',
        options: {
            A: 'Risperidona',
            B: 'Olanzapina',
            C: 'Quetiapina',
            D: 'Clozapina',
            E: 'Aripiprazol',
        },
        correctAnswer: 'D',
        explanation: {
            correct: 'A clozapina apresenta risco de 1-2% de agranulocitose, sendo obrigatório monitoramento hematológico regular (hemograma semanal nas primeiras 18 semanas).',
            wrongA: 'Risperidona não apresenta risco significativo de agranulocitose.',
            wrongB: 'Olanzapina não causa agranulocitose.',
            wrongC: 'Quetiapina não está associada a agranulocitose.',
            wrongE: 'Aripiprazol não causa agranulocitose.',
            keyConcepts: ['Agranulocitose', 'Clozapina', 'Monitoramento hematológico'],
            examTip: 'Clozapina: reservada para esquizofrenia refratária devido aos riscos.',
        },
        source: 'APA Guidelines',
        tags: ['clozapina', 'efeitos adversos', 'antipsicóticos'],
    },
    {
        id: 'pf004',
        theme: 'psicofarmacologia',
        difficulty: 2,
        statement: 'O principal efeito adverso que limita o uso de lítio a longo prazo é:',
        options: {
            A: 'Hepatotoxicidade',
            B: 'Nefrotoxicidade',
            C: 'Agranulocitose',
            D: 'Rabdomiólise',
            E: 'Síndrome neuroléptica maligna',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'O lítio pode causar nefropatia túbulo-intersticial crônica e diabetes insipidus nefrogênico. Monitoramento da função renal é essencial.',
            wrongA: 'Hepatotoxicidade é mais associada ao valproato.',
            wrongC: 'Agranulocitose é associada à clozapina e carbamazepina.',
            wrongD: 'Rabdomiólise não é efeito típico do lítio.',
            wrongE: 'SNM é associada a antipsicóticos.',
            keyConcepts: ['Nefrotoxicidade do lítio', 'Diabetes insipidus', 'Monitoramento renal'],
            examTip: 'Monitorar: função renal, tireoidiana (hipotireoidismo) e litemia.',
        },
        source: 'Kaplan & Sadock',
        tags: ['lítio', 'efeitos adversos', 'monitoramento'],
    },

    // ===== ESQUIZOFRENIA E PSICOSE =====
    {
        id: 'ep001',
        theme: 'esquizofrenia_psicose',
        difficulty: 2,
        statement: 'Qual é a duração mínima de sintomas para diagnóstico de esquizofrenia segundo o DSM-5?',
        options: {
            A: '1 mês',
            B: '3 meses',
            C: '6 meses',
            D: '1 ano',
            E: '2 anos',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'O DSM-5 exige pelo menos 6 meses de perturbação, incluindo pelo menos 1 mês de sintomas da fase ativa (ou menos se tratado).',
            wrongA: '1 mês corresponde apenas à fase ativa mínima.',
            wrongB: '3 meses não atende ao critério de duração.',
            wrongD: '1 ano excede o mínimo necessário.',
            wrongE: '2 anos ultrapassa muito o critério.',
            keyConcepts: ['Critérios temporais DSM-5', 'Fase ativa', 'Fase prodrômica e residual'],
            examTip: 'Transtorno esquizofreniforme: 1-6 meses. Transtorno psicótico breve: <1 mês.',
        },
        source: 'DSM-5',
        tags: ['esquizofrenia', 'critérios diagnósticos', 'duração'],
    },
    {
        id: 'ep002',
        theme: 'esquizofrenia_psicose',
        difficulty: 3,
        statement: 'Paciente com esquizofrenia refratária a dois antipsicóticos adequadamente utilizados. Qual a conduta recomendada?',
        options: {
            A: 'Adicionar benzodiazepínico',
            B: 'Trocar para haloperidol de depósito',
            C: 'Iniciar clozapina',
            D: 'Associar dois antipsicóticos típicos',
            E: 'Eletroconvulsoterapia isolada',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'A clozapina é o único antipsicótico com eficácia comprovada na esquizofrenia refratária (falha a 2 antipsicóticos diferentes, sendo um atípico).',
            wrongA: 'Benzodiazepínicos não tratam sintomas psicóticos.',
            wrongB: 'Haloperidol já seria considerado um dos antipsicóticos que falharam.',
            wrongD: 'Polifarmácia não é recomendada sem tentar clozapina.',
            wrongE: 'ECT pode ser adjuvante, não primeira escolha na refratariedade.',
            keyConcepts: ['Esquizofrenia refratária', 'Clozapina', 'Critérios de refratariedade'],
            examTip: 'Definição de refratariedade: falha a 2 AP (doses e tempo adequados).',
        },
        source: 'APA Guidelines',
        tags: ['esquizofrenia refratária', 'clozapina', 'tratamento'],
    },
    {
        id: 'ep003',
        theme: 'esquizofrenia_psicose',
        difficulty: 2,
        statement: 'Qual dos seguintes NÃO é considerado sintoma negativo da esquizofrenia?',
        options: {
            A: 'Embotamento afetivo',
            B: 'Alogia',
            C: 'Avolição',
            D: 'Delírios persecutórios',
            E: 'Anedonia',
        },
        correctAnswer: 'D',
        explanation: {
            correct: 'Delírios são sintomas positivos. Os sintomas negativos incluem os 5 "As": Afeto embotado, Alogia, Anedonia, Avolição, Associabilidade.',
            wrongA: 'Embotamento afetivo é sintoma negativo clássico.',
            wrongB: 'Alogia (pobreza de discurso) é sintoma negativo.',
            wrongC: 'Avolição (falta de motivação) é sintoma negativo.',
            wrongE: 'Anedonia é considerada sintoma negativo.',
            keyConcepts: ['Sintomas positivos vs negativos', '5 As da esquizofrenia', 'Classificação sintomática'],
            examTip: 'Sintomas negativos respondem mal a antipsicóticos típicos.',
        },
        source: 'DSM-5',
        tags: ['sintomas negativos', 'esquizofrenia', 'classificação'],
    },

    // ===== PSIQUIATRIA INFANTOJUVENIL =====
    {
        id: 'pi001',
        theme: 'psiquiatria_infantojuvenil',
        difficulty: 2,
        statement: 'Qual a idade máxima para início dos sintomas de TDAH, segundo o DSM-5?',
        options: {
            A: '5 anos',
            B: '7 anos',
            C: '10 anos',
            D: '12 anos',
            E: '16 anos',
        },
        correctAnswer: 'D',
        explanation: {
            correct: 'O DSM-5 modificou o critério de idade de início de 7 para 12 anos, reconhecendo que sintomas podem ser identificados mais tardiamente.',
            wrongA: '5 anos era muito restritivo.',
            wrongB: '7 anos era o critério do DSM-IV.',
            wrongC: '10 anos não é o ponto de corte.',
            wrongE: '16 anos ultrapassa o critério.',
            keyConcepts: ['Critérios DSM-5 TDAH', 'Idade de início', 'Mudanças do DSM-IV para DSM-5'],
            examTip: 'DSM-5 mudou: idade de 7→12 anos; 5 sintomas para adultos (vs 6 em crianças).',
        },
        source: 'DSM-5',
        tags: ['TDAH', 'critérios diagnósticos', 'infância'],
    },
    {
        id: 'pi002',
        theme: 'psiquiatria_infantojuvenil',
        difficulty: 2,
        statement: 'Qual medicação é primeira linha no tratamento do TDAH em crianças?',
        options: {
            A: 'Imipramina',
            B: 'Metilfenidato',
            C: 'Fluoxetina',
            D: 'Risperidona',
            E: 'Carbamazepina',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'Metilfenidato (estimulante) é primeira linha no TDAH, com eficácia comprovada e tamanho de efeito grande.',
            wrongA: 'Imipramina é segunda linha, com mais efeitos adversos.',
            wrongC: 'Fluoxetina não trata TDAH.',
            wrongD: 'Risperidona não é indicada para TDAH.',
            wrongE: 'Carbamazepina não tem indicação em TDAH.',
            keyConcepts: ['Tratamento TDAH', 'Estimulantes', 'Metilfenidato'],
            examTip: 'Alternativas: lisdexanfetamina, atomoxetina (não estimulante).',
        },
        source: 'NICE Guidelines',
        tags: ['TDAH', 'tratamento', 'estimulantes'],
    },
    {
        id: 'pi003',
        theme: 'psiquiatria_infantojuvenil',
        difficulty: 3,
        statement: 'Qual característica é mais sugestiva de Transtorno do Espectro Autista nível 1 (necessita apoio)?',
        options: {
            A: 'Ausência completa de fala',
            B: 'Déficits na reciprocidade socioemocional com linguagem preservada',
            C: 'Deficiência intelectual grave',
            D: 'Movimentos estereotipados intensos e constantes',
            E: 'Necessidade de supervisão 24 horas',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'O nível 1 do TEA caracteriza-se por déficits sociais notáveis porém manejáveis, geralmente com linguagem funcional e independência em atividades básicas.',
            wrongA: 'Ausência de fala sugere nível mais grave.',
            wrongC: 'DI grave está mais associada ao nível 3.',
            wrongD: 'Estereotipias intensas são mais comuns em níveis mais graves.',
            wrongE: 'Supervisão 24h indica nível 3.',
            keyConcepts: ['Níveis de gravidade TEA', 'DSM-5', 'Funcionamento adaptativo'],
            examTip: 'Nível 1: "necessita apoio" / Nível 2: "necessita apoio substancial" / Nível 3: "necessita apoio muito substancial".',
        },
        source: 'DSM-5',
        tags: ['autismo', 'TEA', 'níveis de gravidade'],
    },

    // ===== URGÊNCIAS PSIQUIÁTRICAS =====
    {
        id: 'up001',
        theme: 'urgencias_psiquiatricas',
        difficulty: 3,
        statement: 'Paciente em uso de haloperidol desenvolve rigidez muscular, hipertermia (40°C), instabilidade autonômica e CPK elevada. O diagnóstico mais provável é:',
        options: {
            A: 'Síndrome serotoninérgica',
            B: 'Síndrome neuroléptica maligna',
            C: 'Catatonia maligna',
            D: 'Intoxicação por anticolinérgicos',
            E: 'Hipertermia maligna',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'A tétrade da SNM: hipertermia, rigidez muscular, alteração do nível de consciência e instabilidade autonômica, associada ao uso de antipsicóticos.',
            wrongA: 'Síndrome serotoninérgica tem mais clônus e hiperreflexia.',
            wrongC: 'Catatonia maligna é diagnóstico diferencial, mas requer exclusão de SNM.',
            wrongD: 'Intoxicação anticolinérgica causa hipertermia, mas sem rigidez.',
            wrongE: 'Hipertermia maligna ocorre com anestésicos.',
            keyConcepts: ['SNM', 'Tétrade clínica', 'CPK elevada', 'Urgência médica'],
            examTip: 'Tratamento SNM: suspender AP, suporte, dantrolene, bromocriptina.',
        },
        source: 'Emergency Psychiatry',
        tags: ['SNM', 'emergência', 'antipsicóticos'],
    },
    {
        id: 'up002',
        theme: 'urgencias_psiquiatricas',
        difficulty: 2,
        statement: 'Qual o tratamento de primeira linha para agitação psicomotora grave em paciente com esquizofrenia no pronto-socorro?',
        options: {
            A: 'Diazepam oral',
            B: 'Haloperidol IM + prometazina IM',
            C: 'Fluoxetina oral',
            D: 'Carbamazepina oral',
            E: 'Lítio oral',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'A combinação haloperidol + prometazina IM é eficaz e segura para agitação aguda, com rápido início de ação.',
            wrongA: 'Via oral é inadequada para agitação grave.',
            wrongC: 'ISRS não tem efeito na agitação aguda.',
            wrongD: 'Carbamazepina não é indicada para agitação aguda.',
            wrongE: 'Lítio tem início de ação lento.',
            keyConcepts: ['Agitação psicomotora', 'Contenção química', 'Via intramuscular'],
            examTip: 'Alternativas: olanzapina IM, ziprasidona IM, midazolam IM.',
        },
        source: 'TREC Study',
        tags: ['agitação', 'emergência', 'contenção química'],
    },

    // ===== PSICOTERAPIA =====
    {
        id: 'pt001',
        theme: 'psicoterapia',
        difficulty: 2,
        statement: 'A técnica de reestruturação cognitiva é característica de qual abordagem psicoterápica?',
        options: {
            A: 'Psicanálise',
            B: 'Terapia Cognitivo-Comportamental',
            C: 'Psicodrama',
            D: 'Gestalt-terapia',
            E: 'Terapia Sistêmica',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'A reestruturação cognitiva é técnica central da TCC, visando identificar e modificar pensamentos automáticos disfuncionais.',
            wrongA: 'A psicanálise trabalha com associação livre e interpretação.',
            wrongC: 'O psicodrama usa dramatização e role-playing.',
            wrongD: 'A Gestalt foca na experiência presente e awareness.',
            wrongE: 'A terapia sistêmica foca nas interações familiares.',
            keyConcepts: ['TCC', 'Pensamentos automáticos', 'Distorções cognitivas'],
            examTip: 'TCC: modelo cognitivo de Beck, tríade cognitiva na depressão.',
        },
        source: 'Beck Cognitive Therapy',
        tags: ['TCC', 'técnicas', 'reestruturação cognitiva'],
    },
    {
        id: 'pt002',
        theme: 'psicoterapia',
        difficulty: 2,
        statement: 'Qual psicoterapia tem maior nível de evidência para Transtorno de Personalidade Borderline?',
        options: {
            A: 'Psicanálise clássica',
            B: 'Terapia Comportamental Dialética (DBT)',
            C: 'Hipnoterapia',
            D: 'Terapia de Casal',
            E: 'Psicoterapia de apoio',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'A DBT (Linehan) é o tratamento com maior evidência para TPB, focando em regulação emocional, tolerância ao mal-estar, efetividade interpessoal e mindfulness.',
            wrongA: 'Psicanálise tem evidência limitada para TPB.',
            wrongC: 'Hipnoterapia não tem evidência para TPB.',
            wrongD: 'Terapia de casal não é tratamento principal.',
            wrongE: 'Psicoterapia de apoio é menos eficaz que DBT.',
            keyConcepts: ['DBT', 'Transtorno de Personalidade Borderline', 'Linehan'],
            examTip: 'DBT: 4 módulos - regulação emocional, tolerância ao mal-estar, mindfulness, efetividade interpessoal.',
        },
        source: 'Linehan DBT',
        tags: ['DBT', 'personalidade borderline', 'evidência'],
    },

    // ===== ÉTICA E PSIQUIATRIA LEGAL =====
    {
        id: 'el001',
        theme: 'etica_legal',
        difficulty: 2,
        statement: 'Segundo a Lei 10.216/2001, qual modalidade de internação psiquiátrica requer comunicação ao Ministério Público em 72 horas?',
        options: {
            A: 'Internação voluntária',
            B: 'Internação involuntária',
            C: 'Internação compulsória',
            D: 'Todas as modalidades',
            E: 'Nenhuma modalidade requer comunicação',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'A internação involuntária (sem consentimento do paciente, a pedido de terceiro) deve ser comunicada ao MP em 72 horas para fiscalização.',
            wrongA: 'Internação voluntária não requer comunicação ao MP.',
            wrongC: 'Compulsória é determinada pela Justiça, já envolve o sistema judiciário.',
            wrongD: 'Apenas a involuntária requer comunicação específica ao MP.',
            wrongE: 'A involuntária requer comunicação.',
            keyConcepts: ['Lei 10.216/2001', 'Tipos de internação', 'Controle judicial'],
            examTip: 'Lei da Reforma Psiquiátrica: prioriza tratamento comunitário.',
        },
        source: 'Lei 10.216/2001',
        tags: ['internação', 'legislação', 'reforma psiquiátrica'],
    },
    {
        id: 'el002',
        theme: 'etica_legal',
        difficulty: 3,
        statement: 'Em que situação é permitida a quebra do sigilo médico sem autorização do paciente?',
        options: {
            A: 'Pedido do empregador do paciente',
            B: 'Solicitação de familiar próximo',
            C: 'Comunicação de doença de notificação compulsória',
            D: 'Curiosidade de outro profissional de saúde',
            E: 'Reportagem jornalística',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'A notificação compulsória de doenças às autoridades sanitárias é exceção legal ao sigilo médico, visando proteção da saúde pública.',
            wrongA: 'Empregadores não têm direito a informações médicas sem consentimento.',
            wrongB: 'Familiares precisam de autorização do paciente (exceto incapacidade).',
            wrongD: 'Curiosidade não justifica quebra de sigilo.',
            wrongE: 'Mídia jamais tem direito a informações sigilosas.',
            keyConcepts: ['Sigilo médico', 'Exceções legais', 'Notificação compulsória'],
            examTip: 'Outras exceções: justa causa, dever legal, autorização expressa do paciente.',
        },
        source: 'Código de Ética Médica',
        tags: ['sigilo', 'ética', 'notificação compulsória'],
    },

    // ===== NEUROCIÊNCIAS E DIAGNÓSTICO DIFERENCIAL =====
    {
        id: 'nd001',
        theme: 'neurociencias_diagnostico',
        difficulty: 3,
        statement: 'Qual neurotransmissor está mais diretamente implicado na fisiopatologia dos sintomas positivos da esquizofrenia?',
        options: {
            A: 'GABA',
            B: 'Glutamato',
            C: 'Dopamina',
            D: 'Acetilcolina',
            E: 'Noradrenalina',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'A hipótese dopaminérgica postula hiperatividade dopaminérgica na via mesolímbica como base dos sintomas positivos.',
            wrongA: 'GABA está mais relacionado à ansiedade.',
            wrongB: 'Glutamato é importante, mas a hipótese dopaminérgica é clássica.',
            wrongD: 'Acetilcolina está mais relacionada à cognição.',
            wrongE: 'Noradrenalina não é central na esquizofrenia.',
            keyConcepts: ['Hipótese dopaminérgica', 'Via mesolímbica', 'Sintomas positivos'],
            examTip: 'Via mesolímbica: sintomas positivos. Via mesocortical: sintomas negativos e cognitivos.',
        },
        source: 'Stahl Psychopharmacology',
        tags: ['dopamina', 'esquizofrenia', 'neurociências'],
    },
    {
        id: 'nd002',
        theme: 'neurociencias_diagnostico',
        difficulty: 2,
        statement: 'Paciente com confusão mental aguda, desorientação, alucinações visuais e flutuação do nível de consciência. Qual o diagnóstico mais provável?',
        options: {
            A: 'Demência de Alzheimer',
            B: 'Delirium',
            C: 'Esquizofrenia',
            D: 'Transtorno conversivo',
            E: 'Transtorno depressivo com sintomas psicóticos',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'O delirium caracteriza-se por alteração aguda da consciência, flutuação, déficit atencional e frequentemente alucinações visuais.',
            wrongA: 'Demência é crônica e progressiva, sem flutuação marcante.',
            wrongC: 'Esquizofrenia não cursa com alteração do nível de consciência.',
            wrongD: 'Conversivo não apresenta esse quadro.',
            wrongE: 'Depressão psicótica não altera consciência assim.',
            keyConcepts: ['Delirium', 'Alteração de consciência', 'Causa orgânica'],
            examTip: 'Sempre investigar causa orgânica no delirium: infecção, metabólica, medicamentos.',
        },
        source: 'Kaplan & Sadock',
        tags: ['delirium', 'diagnóstico diferencial', 'emergência'],
    },

    // ===== TRANSTORNOS DE ANSIEDADE =====
    {
        id: 'ta001',
        theme: 'transtornos_ansiedade',
        difficulty: 2,
        statement: 'Qual é a duração mínima de preocupação excessiva para diagnóstico de Transtorno de Ansiedade Generalizada?',
        options: {
            A: '1 mês',
            B: '3 meses',
            C: '6 meses',
            D: '1 ano',
            E: '2 anos',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'O TAG requer preocupação excessiva na maioria dos dias por pelo menos 6 meses, associada a pelo menos 3 sintomas somáticos.',
            wrongA: '1 mês é insuficiente.',
            wrongB: '3 meses não atende ao critério.',
            wrongD: '1 ano excede o mínimo.',
            wrongE: '2 anos é critério para distimia.',
            keyConcepts: ['TAG', 'Critérios temporais', 'Sintomas somáticos'],
            examTip: 'Sintomas somáticos do TAG: tensão muscular, irritabilidade, insônia, fadiga.',
        },
        source: 'DSM-5',
        tags: ['TAG', 'ansiedade', 'critérios diagnósticos'],
    },
    {
        id: 'ta002',
        theme: 'transtornos_ansiedade',
        difficulty: 2,
        statement: 'Qual o tratamento de primeira linha para Transtorno de Pânico?',
        options: {
            A: 'Benzodiazepínicos isolados',
            B: 'Antipsicóticos atípicos',
            C: 'ISRS',
            D: 'Anticonvulsivantes',
            E: 'Betabloqueadores',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'ISRS são primeira linha no transtorno de pânico, com eficácia comprovada e bom perfil de segurança a longo prazo.',
            wrongA: 'Benzodiazepínicos são úteis no início, mas não primeira linha isolada.',
            wrongB: 'Antipsicóticos não são indicados.',
            wrongD: 'Anticonvulsivantes não são primeira linha.',
            wrongE: 'Betabloqueadores tratam sintomas físicos, não o transtorno.',
            keyConcepts: ['Tratamento do pânico', 'ISRS', 'Farmacoterapia'],
            examTip: 'ISRS: início de ação em 2-4 semanas. Iniciar em dose baixa para evitar piora inicial.',
        },
        source: 'APA Guidelines',
        tags: ['pânico', 'tratamento', 'ISRS'],
    },
    {
        id: 'ta003',
        theme: 'transtornos_ansiedade',
        difficulty: 3,
        statement: 'Case de paciente que desenvolve sintomas após trauma. Qual critério temporal diferencia Transtorno de Estresse Agudo de TEPT?',
        options: {
            A: 'TEA: 1-7 dias; TEPT: >7 dias',
            B: 'TEA: 3 dias a 1 mês; TEPT: >1 mês',
            C: 'TEA: 1-3 meses; TEPT: >3 meses',
            D: 'TEA: <6 meses; TEPT: >6 meses',
            E: 'Não há diferença temporal, apenas de sintomas',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'TEA: sintomas de 3 dias a 1 mês após o trauma. TEPT: sintomas persistem por mais de 1 mês.',
            wrongA: '1-7 dias é muito curto para TEA.',
            wrongC: '3 meses não é o ponto de corte.',
            wrongD: '6 meses não é critério relevante.',
            wrongE: 'Há diferença temporal clara.',
            keyConcepts: ['TEA vs TEPT', 'Critérios temporais', 'Trauma'],
            examTip: 'TEPT pode ter início tardio: sintomas após 6 meses do trauma.',
        },
        source: 'DSM-5',
        tags: ['TEPT', 'TEA', 'trauma'],
    },

    // ===== TRANSTORNOS DE PERSONALIDADE =====
    {
        id: 'tp001',
        theme: 'transtornos_personalidade',
        difficulty: 2,
        statement: 'Qual cluster de transtornos de personalidade inclui os transtornos paranoide, esquizoide e esquizotípico?',
        options: {
            A: 'Cluster A',
            B: 'Cluster B',
            C: 'Cluster C',
            D: 'Cluster D',
            E: 'Não há classificação em clusters',
        },
        correctAnswer: 'A',
        explanation: {
            correct: 'O Cluster A inclui os transtornos "excêntricos": paranoide, esquizoide e esquizotípico.',
            wrongB: 'Cluster B são os "dramáticos": antissocial, borderline, histriônico, narcisista.',
            wrongC: 'Cluster C são os "ansiosos": evitativo, dependente, obsessivo-compulsivo.',
            wrongD: 'Não existe Cluster D.',
            wrongE: 'A classificação em clusters existe no DSM.',
            keyConcepts: ['Clusters de personalidade', 'Transtornos do Cluster A', 'Classificação DSM'],
            examTip: 'A: estranhos. B: dramáticos. C: ansiosos.',
        },
        source: 'DSM-5',
        tags: ['personalidade', 'clusters', 'classificação'],
    },
    {
        id: 'tp002',
        theme: 'transtornos_personalidade',
        difficulty: 2,
        statement: 'Instabilidade nas relações interpessoais, autoimagem e afetos, com impulsividade marcante, é característica de qual transtorno de personalidade?',
        options: {
            A: 'Transtorno de Personalidade Narcisista',
            B: 'Transtorno de Personalidade Histriônica',
            C: 'Transtorno de Personalidade Borderline',
            D: 'Transtorno de Personalidade Esquizotípica',
            E: 'Transtorno de Personalidade Dependente',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'O TPB caracteriza-se por instabilidade afetiva, relacional e de autoimagem, com impulsividade, medo de abandono e autolesão.',
            wrongA: 'Narcisista: grandiosidade, necessidade de admiração.',
            wrongB: 'Histriônico: busca de atenção, expressividade emocional.',
            wrongD: 'Esquizotípico: excentricidade, ideias de referência.',
            wrongE: 'Dependente: submissão, medo de separação.',
            keyConcepts: ['TPB', 'Instabilidade', 'Impulsividade'],
            examTip: 'TPB: 9 critérios, necessários 5. Autolesão é comum.',
        },
        source: 'DSM-5',
        tags: ['borderline', 'personalidade', 'diagnóstico'],
    },

    // ===== DEPENDÊNCIA QUÍMICA =====
    {
        id: 'dq001',
        theme: 'dependencia_quimica',
        difficulty: 2,
        statement: 'Qual medicação é primeira linha para tratamento da dependência de álcool?',
        options: {
            A: 'Diazepam',
            B: 'Naltrexona',
            C: 'Clonidina',
            D: 'Metilfenidato',
            E: 'Antipsicótico típico',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'Naltrexona (antagonista opioide) reduz o reforço positivo do álcool e o craving, sendo primeira linha junto com acamprosato e dissulfiram.',
            wrongA: 'Diazepam é para abstinência aguda, não manutenção.',
            wrongC: 'Clonidina é para abstinência de opioides.',
            wrongD: 'Metilfenidato não é indicado.',
            wrongE: 'Antipsicóticos não são tratamento da dependência.',
            keyConcepts: ['Tratamento do alcoolismo', 'Naltrexona', 'Farmacoterapia'],
            examTip: 'Opções: naltrexona, acamprosato, dissulfiram. Topiramato off-label.',
        },
        source: 'APA Guidelines',
        tags: ['alcoolismo', 'tratamento', 'naltrexona'],
    },
    {
        id: 'dq002',
        theme: 'dependencia_quimica',
        difficulty: 3,
        statement: 'Paciente com abstinência alcoólica apresenta tremores, sudorese, taquicardia e alucinações visuais. Qual a conduta?',
        options: {
            A: 'Antipsicótico em dose alta',
            B: 'Benzodiazepínico + tiamina',
            C: 'ISRS',
            D: 'Apenas observação',
            E: 'Naltrexona imediata',
        },
        correctAnswer: 'B',
        explanation: {
            correct: 'Benzodiazepínicos são primeira linha na abstinência alcoólica. Tiamina previne encefalopatia de Wernicke.',
            wrongA: 'Antipsicóticos isolados aumentam risco de convulsão.',
            wrongC: 'ISRS não tem papel na abstinência aguda.',
            wrongD: 'Abstinência alcoólica pode ser fatal, requer tratamento.',
            wrongE: 'Naltrexona é para manutenção, não abstinência aguda.',
            keyConcepts: ['Abstinência alcoólica', 'Delirium tremens', 'Tiamina'],
            examTip: 'SEMPRE dar tiamina ANTES de glicose para evitar Wernicke.',
        },
        source: 'Emergency Psychiatry',
        tags: ['abstinência', 'álcool', 'emergência'],
    },

    // ===== PSIQUIATRIA GERIÁTRICA =====
    {
        id: 'pg001',
        theme: 'psiquiatria_geriatrica',
        difficulty: 2,
        statement: 'Qual o tipo mais comum de demência?',
        options: {
            A: 'Demência vascular',
            B: 'Demência com corpos de Lewy',
            C: 'Doença de Alzheimer',
            D: 'Demência frontotemporal',
            E: 'Demência por Parkinson',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'A Doença de Alzheimer é responsável por 60-70% dos casos de demência, caracterizada por perda de memória episódica progressiva.',
            wrongA: 'Vascular é a segunda mais comum.',
            wrongB: 'Lewy corresponde a cerca de 10-15%.',
            wrongD: 'Frontotemporal é menos comum.',
            wrongE: 'Demência por Parkinson é menos prevalente.',
            keyConcepts: ['Alzheimer', 'Epidemiologia das demências', 'Memória episódica'],
            examTip: 'Ordem de frequência: Alzheimer > Vascular > Lewy > Frontotemporal.',
        },
        source: 'WHO',
        tags: ['demência', 'Alzheimer', 'epidemiologia'],
    },
    {
        id: 'pg002',
        theme: 'psiquiatria_geriatrica',
        difficulty: 3,
        statement: 'Alucinações visuais bem formadas e flutuação cognitiva são características de qual demência?',
        options: {
            A: 'Doença de Alzheimer',
            B: 'Demência vascular',
            C: 'Demência com corpos de Lewy',
            D: 'Demência frontotemporal variante comportamental',
            E: 'Hidrocefalia de pressão normal',
        },
        correctAnswer: 'C',
        explanation: {
            correct: 'A demência com corpos de Lewy caracteriza-se pela tríade: alucinações visuais, flutuação cognitiva e parkinsonismo.',
            wrongA: 'Alzheimer raramente tem alucinações visuais precoces.',
            wrongB: 'Vascular tem padrão em degraus.',
            wrongD: 'Frontotemporal tem alterações comportamentais e de linguagem.',
            wrongE: 'HPN tem tríade: demência, incontinência, marcha atáxica.',
            keyConcepts: ['Demência com corpos de Lewy', 'Alucinações visuais', 'Flutuação'],
            examTip: 'Lewy: sensibilidade a antipsicóticos (pioram parkinsonismo).',
        },
        source: 'Kaplan & Sadock',
        tags: ['Lewy', 'demência', 'diagnóstico diferencial'],
    },
];
