import { Question } from '../types';

export const questions2025Part2: Question[] = [
    {
        id: 'p2025_007',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\ncom rela\u00e7\u00e3o \u00e0 Aten\u00e7\u00e3o e Preven\u00e7\u00e3o, h\u00e1 tr\u00eas n\u00edveis de aten\u00e7\u00e3o:\nAten\u00e7\u00e3o b\u00e1sica ou prim\u00e1ria: a Aten\u00e7\u00e3o Prim\u00e1ria \u00e0 Sa\u00fade (APS) \u00e9 o primeiro n\u00edvel\nde aten\u00e7\u00e3o em sa\u00fade e se caracteriza por um conjunto de a\u00e7\u00f5es, nos \u00e2mbitos\nindividual e coletivo, que abrange a promo\u00e7\u00e3o e a prote\u00e7\u00e3o da sa\u00fade, a preven\u00e7\u00e3o\nde agravos, o diagn\u00f3stico, o tratamento, a reabilita\u00e7\u00e3o, a redu\u00e7\u00e3o de danos e a\nmanuten\u00e7\u00e3o da sa\u00fade com o objetivo de desenvolver uma aten\u00e7\u00e3o integral que\nimpacte positivamente na situa\u00e7\u00e3o de sa\u00fade das coletividades. Trata-se da\nprincipal porta de entrada do Sistema \u00danico de Sa\u00fade (SUS) e do centro de\ncomunica\u00e7\u00e3o com toda a Rede de Aten\u00e7\u00e3o do SUS. Na Portaria do Minist\u00e9rio da\nSa\u00fade n\u00ba648/2006, o termo utilizado \u00e9 aten\u00e7\u00e3o b\u00e1sica. A aten\u00e7\u00e3o b\u00e1sica tem a\nsa\u00fade da fam\u00edlia como estrat\u00e9gia priorit\u00e1ria, de acordo com os preceitos do SUS, e\n\u00e9 entendida como o primeiro n\u00edvel da aten\u00e7\u00e3o \u00e0 sa\u00fade; emprega tecnologia de\nbaixa densidade, que inclui um rol de procedimentos mais simples e baratos,\ncapazes de atender \u00e0 maior parte dos problemas comuns de sa\u00fade da\ncomunidade e n\u00e3o deve ser confundida com preven\u00e7\u00e3o prim\u00e1ria, que s\u00e3o os\nrecursos e estrat\u00e9gias usados para evitar a incid\u00eancia de doen\u00e7as e transtornos\nmentais.\nA Aten\u00e7\u00e3o Secund\u00e1ria, \u201cou de m\u00e9dia complexidade [...], \u00e9 formada pelos servi\u00e7os\nespecializados em n\u00edvel ambulatorial e hospitalar, com densidade tecnol\u00f3gica\nintermedi\u00e1ria entre a aten\u00e7\u00e3o prim\u00e1ria e a terci\u00e1ria\u201d. A m\u00e9dia complexidade\nambulatorial \u00e9 composta por a\u00e7\u00f5es e servi\u00e7os que visam atender aos principais\nproblemas e agravos de sa\u00fade da popula\u00e7\u00e3o, cuja complexidade da assist\u00eancia\nna pr\u00e1tica cl\u00ednica demande a disponibilidade de profssionais especializados e a\nutiliza\u00e7\u00e3o de recursos tecnol\u00f3gicos, para o apoio diagn\u00f3stico e tratamento. A\npreven\u00e7\u00e3o secund\u00e1ria consiste na detec\u00e7\u00e3o precoce e no tratamento efetivo de\ndoen\u00e7as e transtornos mentais e do comportamento, visando o restabelecimento\nda sa\u00fade individual e a preven\u00e7\u00e3o de complica\u00e7\u00f5es e sequelas, e deve ser feita\nem todos os n\u00edveis de servi\u00e7os de aten\u00e7\u00e3o \u00e0 sa\u00fade.\nA Aten\u00e7\u00e3o Terci\u00e1ria, ou de alta complexidade, \u201c\u00e9 o conjunto de procedimentos\nque, no contexto do SUS, envolve alta tecnologia e alto custo [...] propiciando\nacesso a servi\u00e7os qualifcados, integrando-os aos demais n\u00edveis de aten\u00e7\u00e3o \u00e0\nsa\u00fade (aten\u00e7\u00e3o b\u00e1sica e de m\u00e9dia complexidade)\u201d. Assim, o que diferencia os\nlocais de atendimento \u00e9 a complexidade, mas a preven\u00e7\u00e3o terci\u00e1ria abrange\ninterven\u00e7\u00f5es de mais longa dura\u00e7\u00e3o para tratamentos de manuten\u00e7\u00e3o, preven\u00e7\u00e3o\nde reca\u00eddas, redu\u00e7\u00e3o de sequelas e incapacita\u00e7\u00e3o. Parte disso poderia ser\ndenominada preven\u00e7\u00e3o quatern\u00e1ria, por n\u00e3o necessitar dos recursos m\u00e9dicos\ncomplexos e envolver outras compet\u00eancias profssionais, principalmente das\n\u00e1reas relacionadas com a reabilita\u00e7\u00e3o f\u00edsica e psicossocial, mas esse termo\ntamb\u00e9m foi utilizado para representar a preven\u00e7\u00e3o de excessos do uso de\ninterven\u00e7\u00f5es e procedimentos m\u00e9dicos.\nDe acordo com a refer\u00eancia e com os conceitos expostos, assinale o n\u00edvel de\naten\u00e7\u00e3o no qual a reabilita\u00e7\u00e3o psicossocial se enquadra.",
        options: {
            A: "Aten\u00e7\u00e3o b\u00e1sica.",
            B: "Aten\u00e7\u00e3o secund\u00e1ria.",
            C: "Preven\u00e7\u00e3o secund\u00e1ria.",
            D: "Preven\u00e7\u00e3o terci\u00e1ria.",
            E: "Preven\u00e7\u00e3o quatern\u00e1ria.",
        },
        correctAnswer: 'C',
        comment: ") Inconsist\u00eancia diagn\u00f3stica",
    },
    {
        id: 'p2025_008',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\no Brasil participou do Cons\u00f3rcio WMHS (World Mental Health Survey Initiative)\ncom o estudo S\u00e3o Paulo Megacity Mental Health Survey (SPMHS) que avaliou uma\namostra probabil\u00edstica da popula\u00e7\u00e3o geral adulta residente na regi\u00e3o\nmetropolitana de S\u00e3o Paulo (RMSP), composta por 39 munic\u00edpios. Foram\nrealizadas 5.037 entrevistas entre os anos de 2005 e 2007. Os objetivos do SPMHS\neram: fornecer estimativas de preval\u00eancia ao longo da vida e de 12 meses para\numa ampla gama de transtornos mentais na popula\u00e7\u00e3o em geral; identifcar\ncorrelatos de morbidade psiqui\u00e1trica, bem como sua gravidade e preju\u00edzo\nassociado; determinar os padr\u00f5es de uso dos servi\u00e7os de sa\u00fade; e estimar a carga\nglobal de transtornos mentais na cidade. Assinale o transtorno de controle dos\nimpulsos mais prevalente nessa amostra.",
        options: {
            A: "Jogo patol\u00f3gico.",
            B: "Transtorno de conduta.",
            C: "Transtorno de oposi\u00e7\u00e3o desafante.",
            D: "Transtorno explosivo intermitente.",
            E: "Transtorno de d\u00e9fcit de aten\u00e7\u00e3o e hiperatividade.",
        },
        correctAnswer: 'A',
        comment: ") Pacientes que respondem ao tratamento antidepressivo apresentam uma recupera\u00e7\u00e3o ao menos parcial do volume da subst\u00e2ncia cinzenta, o que\nn\u00e3o foi observado naqueles que n\u00e3o respondem ao tratamento.\nB) As hiperintensidades de sinal na subst\u00e2ncia branca permanecem est\u00e1veis em pacientes com o primeiro epis\u00f3dio ap\u00f3s os 60 anos de idade.\nC) Altera\u00e7\u00f5es estruturais na subst\u00e2ncia branca n\u00e3o podem estar associadas a disfun\u00e7\u00e3o de circuitos neurais na depress\u00e3o.\nD) N\u00e3o h\u00e1 altera\u00e7\u00f5es sugestivas de acelera\u00e7\u00e3o do envelhecimento cerebral no TDM.\nE) As rela\u00e7\u00f5es ventr\u00edculos\u2013c\u00e9rebro est\u00e3o inalteradas no TDM.\nP\u00e1gina 714\nAlternativa correta: A \u2014 Pacientes que respondem ao tratamento\nantidepressivo apresentam recupera\u00e7\u00e3o parcial do volume da subst\u00e2ncia\ncinzenta.\nB \u2014 Incorreta: O texto afirma que hiperintensidades de subst\u00e2ncia branca s\u00e3o mais\ncomuns e associam-se ao primeiro epis\u00f3dio ap\u00f3s os 60 anos, n\u00e3o que permane\u00e7am\nest\u00e1veis.\nC \u2014 Incorreta: O tratado diz explicitamente que altera\u00e7\u00f5es de subst\u00e2ncia branca\npodem estar por tr\u00e1s de disfun\u00e7\u00f5es de circuitos neurais.\nD \u2014 Incorreta: O texto mostra evid\u00eancia de acelera\u00e7\u00e3o do envelhecimento cerebral,\ncomo idade neuroanat\u00f4mica maior e redu\u00e7\u00e3o acelerada do putame.\nE \u2014 Incorreta: O tratado afirma aumento da raz\u00e3o ventr\u00edculos-c\u00e9rebro, logo n\u00e3o est\u00e3o\ninalteradas.",
    },
    {
        id: 'p2025_012',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\na organiza\u00e7\u00e3o dos sintomas p\u00f3s-traum\u00e1ticos na defni\u00e7\u00e3o de TEPT adotada no\nDSM-5 \u00e9 derivada do modelo TEPT-disforia. No DSM-5, sintomas p\u00f3s-traum\u00e1ticos\nest\u00e3o divididos em quatro agrupamentos: revivesc\u00eancia (agrupamento B), esquiva\n(agrupamento C), altera\u00e7\u00f5es negativas na cogni\u00e7\u00e3o e no humor (agrupamento D) e\naltera\u00e7\u00f5es marcantes na excita\u00e7\u00e3o e na reatividade (agrupamento E). Assinale o\nsintoma componente do agrupamento B.",
        options: {
            A: "Incapacidade de recordar um aspecto importante do evento traum\u00e1tico.",
            B: "Esfor\u00e7os para evitar recorda\u00e7\u00f5es, pensamentos ou sentimentos angustiantes\nacerca de ou associados de perto ao evento traum\u00e1tico.",
            C: "Estado emocional negativo persistente.",
            D: "Sonhos angustiantes recorrentes.",
            E: "Hipervigil\u00e2ncia",
        },
        correctAnswer: 'A',
        comment: ") Redu\u00e7\u00e3o da densidade de neuritos.\nB) Aumento da difusividade m\u00e9dia.\nC) Redu\u00e7\u00e3o da fra\u00e7\u00e3o de \u00e1gua livre.\nD) Redu\u00e7\u00e3o da anisotropia fracional.\nE) Aumentos focais no \u00cdndice de Orienta\u00e7\u00e3o da Dispers\u00e3o.\nP\u00e1gina 1260\nNo exame de RM, eventualmente, pode mostrar atrofia discreta em regi\u00f5es parietooccipitais. Al\u00e9m disso, estudos com imagem por tensor de difus\u00e3o (DTI) t\u00eam\ndemonstrado redu\u00e7\u00e3o da anisotropia fracional (FA) em regi\u00f5es parieto-occipitais",
    },
    {
        id: 'p2025_017',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\nh\u00e1 diversos tipos de varia\u00e7\u00f5es ou anormalidades gen\u00e9ticas que podem ocorrer em\num indiv\u00edduo, podendo levar a altera\u00e7\u00f5es de comportamento, as quais podem\nenvolver um ou mais genes. A seguir, s\u00e3o descritas as principais altera\u00e7\u00f5es\nencontradas ao longo do genoma:\nI. Altera\u00e7\u00f5es de perda ou ganho de um cromossomo (aneuploidia), que ocorrem\ndurante a divis\u00e3o celular na fase embrion\u00e1ria (por exemplo, s\u00edndrome de Down,\ntrissomia do 21) ou de Turner (por exemplo, monossomia do X).\nII. Variantes estruturais gen\u00f4micas (SVs), que s\u00e3o fragmentos cromoss\u00f4micos\ndeslocados (por exemplo, invers\u00e3o, transloca\u00e7\u00e3o).\nIII. Dele\u00e7\u00f5es e duplica\u00e7\u00f5es observadas em SVs, que s\u00e3o chamadas de varia\u00e7\u00f5es\ndo n\u00famero de c\u00f3pias (CNVs) e arbitrariamente defnidas como sequ\u00eancias\nmaiores que mil nucleot\u00eddeos (1.000nt). Essas varia\u00e7\u00f5es s\u00e3o numerosas e existem\nao longo do genoma de qualquer pessoa, podendo causar doen\u00e7as de acordo\ncom a sua localiza\u00e7\u00e3o (duplica\u00e7\u00e3o ou dele\u00e7\u00e3o de fragmento de DNA), como em\nalgumas formas de transtorno do espectro autista (TEA).\nIV. Varia\u00e7\u00f5es de repeti\u00e7\u00f5es de sequ\u00eancias espec\u00edfcas (ou \u201cblocos\u201d) de DNA em\ngeral, com tamanho de algumas centenas de nucleot\u00eddeos, que s\u00e3o chamadas de\nvaria\u00e7\u00f5es do n\u00famero de repeti\u00e7\u00f5es (VNTRs, do ingl\u00eas variable number tandem\nrepeats), em que cada \u201cbloco\u201d a ser repetido pode ser constitu\u00eddo de 7 a 100\nnucleot\u00eddeos. J\u00e1 as repeti\u00e7\u00f5es de sequ\u00eancias curtas (STRs, do ingl\u00eas short tandem\nrepeats) apresentam sequ\u00eancias espec\u00edfcas entre 2 e 6 nucleot\u00eddeos. Por\nexemplo, na doen\u00e7a de Huntington, as pessoas afetadas apresentam 28 ou mais\nrepeti\u00e7\u00f5es do trinucleot\u00eddeo CAG no gene HTT localizado no cromossomo 4 (a\nsequ\u00eancia CAG aparece repetida em, no m\u00e1ximo, 27 vezes em pessoas n\u00e3o\nafetadas).\nV. Indels (inser\u00e7\u00e3o/dele\u00e7\u00e3o), que s\u00e3o fragmentos de DNA variando entre 1 e 50\nnucleot\u00eddeos, expandindo (inser\u00e7\u00e3o) ou contraindo (dele\u00e7\u00e3o) o genoma.\nVI. Variante de nucleot\u00eddeo \u00fanico (SNV, do ingl\u00eas single nucleotide variant), que \u00e9 a\nmenor unidade de varia\u00e7\u00e3o gen\u00e9tica e a mais usada em estudos gen\u00e9ticos.\nUma das principais altera\u00e7\u00f5es encontradas ao longo do genoma \u00e9 chamada de\npolimorfsmo de nucleot\u00eddeo \u00fanico (SNP, do ingl\u00eas single nucleotide\npolymorphism). De acordo com a refer\u00eancia, o que s\u00e3o os SNPs?",
        options: {
            A: "Os SNPs s\u00e3o SNVs comuns na popula\u00e7\u00e3o geral.",
            B: "Os SNPs s\u00e3o SNVs extremamente raros.",
            C: "Os SNPs s\u00e3o VNTRs de sequ\u00eancias \u00fanicas.",
            D: "Os SNPs s\u00e3o SVs raras.",
            E: "Os SNPs s\u00e3o SVs comuns na popula\u00e7\u00e3o geral.",
        },
        correctAnswer: 'D',
        comment: ") Preconceito.",
    },
    {
        id: 'p2025_021',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\na partir da compreens\u00e3o e que a dopamina exerce papel apenas parcial na\nfsiopatologia da esquizofrenia, surgiu a hip\u00f3tese do \u00e1cido quinur\u00eanico para a\ndoen\u00e7a. Essa hip\u00f3tese postula que um desequil\u00edbrio do sistema imunol\u00f3gico com\npredomin\u00e2ncia de citocinas pr\u00f3-in\ufb02amat\u00f3rias (por exemplo, IL-6) ativaria a enzima\nindoleamina 2,3-dioxigenase, que intensifca o metabolismo do triptofano para a\nvia da quinurenina, resultando em um aumento da produ\u00e7\u00e3o do \u00e1cido\nquinur\u00eanico, antagonista de um receptor espec\u00edfco. Em excesso, o \u00e1cido\nquinur\u00eanico levaria a uma hipofun\u00e7\u00e3o desse receptor, envolvido na patofsiologia\nda esquizofrenia. Assinale o receptor em quest\u00e3o.",
        options: {
            A: "5HT3.",
            B: "NMDA.",
            C: "5HT2A.",
            D: "5HT1A.",
            E: "Colin\u00e9rgico muscar\u00ednico.",
        },
        correctAnswer: 'B',
        comment: ") Sistema de Processos Sociais",
    },
    {
        id: 'p2025_023',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\nos elementos envolvidos na etiologia da depress\u00e3o p\u00f3s-parto incluem redu\u00e7\u00e3o\ndos n\u00edveis de horm\u00f4nios reprodutivos, como a allopregnanolona, altera\u00e7\u00f5es\ntireoidianas, disfun\u00e7\u00f5es no eixo hipot\u00e1lamo-hip\u00f3fse-adrenal e anormalidades do\ncolesterol e \u00e1cidos graxos. Estudos com humanos e em roedores demonstram\noscila\u00e7\u00f5es de estradiol, corticosterona, horm\u00f4nio liberador corticotr\u00f3pico e\noxitocina durante o per\u00edodo perinatal. Durante a gesta\u00e7\u00e3o, as taxas de\nprogesterona s\u00e3o aproximadamente 20 vezes maiores. Por\u00e9m,\nconcomitantemente \u00e0 expuls\u00e3o da placenta, progesterona e estradiol exibem\nabrupta queda, sugerindo a hip\u00f3tese de que um \"estado de retirada de estradiol\"\ndurante as primeiras semanas ap\u00f3s o parto contribui para a depress\u00e3o p\u00f3s-parto.\nQual \u00e9 o aumento estimado nos n\u00edveis de estradiol durante a gesta\u00e7\u00e3o?",
        options: {
            A: "20 vezes superiores.",
            B: "200 a 300 vezes superiores.",
            C: "100 a 150 vezes superiores.",
            D: "300 a 400 vezes superiores.",
            E: "N\u00e3o h\u00e1 aumento nos n\u00edveis de estradiol.",
        },
        correctAnswer: 'E',
        comment: ") Coer\u00eancia central",
    },
    {
        id: 'p2025_024',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia AMERICAN PSYCHIATRIC ASSOCIATION. Manual\nDiagn\u00f3stico e Estat\u00edstico de Transtornos Mentais. 5. ed. (DSM-5). Artmed, 2014, e\nem rela\u00e7\u00e3o ao transtorno pedof\u00edlico, diz-se que a sua preval\u00eancia na popula\u00e7\u00e3o \u00e9\ndesconhecida. A preval\u00eancia mais alta poss\u00edvel para o transtorno entre os\nindiv\u00edduos do sexo masculino \u00e9 de cerca de 3 a 5%. Nos do sexo feminino, a\npreval\u00eancia \u00e9 ainda mais incerta, embora possivelmente seja uma fra\u00e7\u00e3o pequena\ndaquela observada no sexo masculino. Em rela\u00e7\u00e3o aos fatores de risco e\nprogn\u00f3stico desse transtorno, eles s\u00e3o divididos em tr\u00eas grupos: temperamentais,\nambientais e gen\u00e9ticos, e fsiol\u00f3gicos. Em rela\u00e7\u00e3o aos fatores de risco e\nprogn\u00f3stico do transtorno pedof\u00edlico, e de acordo com a refer\u00eancia, assinale a\nalternativa incorreta.",
        options: {
            A: "Fator ambiental: est\u00e1 claro que h\u00e1 uma correla\u00e7\u00e3o que re\ufb02ete a in\ufb02u\u00eancia\ncausal do abuso sexual na inf\u00e2ncia com a pedoflia na vida adulta.",
            B: "Fator temperamental: o transtorno da personalidade antissocial pode ser\nconsiderado um fator de risco para transtorno pedof\u00edlico em homens com\npedoflia.",
            C: "Fator temperamental: parece existir intera\u00e7\u00e3o entre pedoflia e comportamento\nantissocial, de modo que indiv\u00edduos do sexo masculino com ambos os tra\u00e7os\napresentam maior propens\u00e3o a agir sexualmente com crian\u00e7as.",
            D: "Fator ambiental: homens adultos com pedoflia frequentemente relatam terem\nsido sexualmente abusados quando crian\u00e7as.",
            E: "Fator gen\u00e9tico e fsiol\u00f3gico: h\u00e1 algumas evid\u00eancias de que perturba\u00e7\u00e3o do\nneurodesenvolvimento na vida intrauterina aumenta a probabilidade de\ndesenvolvimento de orienta\u00e7\u00e3o pedof\u00edlica.",
        },
        correctAnswer: 'B',
        comment: ") Dosagem de prolactina.",
    },
    {
        id: 'p2025_040',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\nh\u00e1 um sentido original do termo psicofobia, no entanto, esse termo tem sido\nusado em sentido n\u00e3o cl\u00ednico no Brasil, podendo, nesse contexto, ser defnido\ncomo o \"preconceito ou a discrimina\u00e7\u00e3o contra pessoas com transtornos mentais\nou defci\u00eancias intelectuais\". Nesse aspecto, o sufxo \u201cfobia\u201d n\u00e3o \u00e9 usado de forma\ncl\u00ednica, mas no sentido de atitude negativa ou preconceituosa, tendo seu uso\ndifundido em iniciativas antidiscriminat\u00f3rias. Assinale o signifcado original do\ntermo psicofobia.",
        options: {
            A: "Cren\u00e7a irracional de que estat\u00edsticas relativas a doen\u00e7as mentais s\u00e3o super\nestimadas.",
            B: "Medo exagerado da conviv\u00eancia com pacientes psiqui\u00e1tricos.",
            C: "Descren\u00e7a n\u00e3o fundamentada em tratamentos psicoter\u00e1picos.",
            D: "Ceticismo inamov\u00edvel quanto a avan\u00e7os neurocient\u00edfcos.",
            E: "Medo exagerado e irracional da mente.",
        },
        correctAnswer: 'A',
        comment: ") Por perito detentor de Registro de Qualifica\u00e7\u00e3o de Especialista (RQE) na \u00e1rea de\nPsiquiatria Forense, nomeado com essa finalidade.\nB) Por consenso de equipe multidisciplinar de Centro de Aten\u00e7\u00e3o Psicossocial,\ndesignada para tal avalia\u00e7\u00e3o.\nC) Pelo respons\u00e1vel t\u00e9cnico do estabelecimento no qual tenha sido detectada sua\nnecessidade.\nD) Pelo juiz competente.\nE) Pelo especialista respons\u00e1vel pelo tratamento.\nExplica\u00e7\u00e3o objetiva\nSegundo a Lei n\u00ba 10.216/2001, a interna\u00e7\u00e3o compuls\u00f3ria \u00e9 aquela:\ndeterminada judicialmente,\nsem consentimento do usu\u00e1rio,\ne independente da vontade da fam\u00edlia.\nOu seja, somente o juiz pode determinar esse tipo de interna\u00e7\u00e3o \u2014 ap\u00f3s avalia\u00e7\u00e3o\nm\u00e9dica formal que subsidia a decis\u00e3o.\nResposta: D) Pelo juiz competente.",
    },
    {
        id: 'p2025_041',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia BRASIL. Presid\u00eancia da Rep\u00fablica. Casa Civil.\nSubchefa para assuntos jur\u00eddicos. Lei n\u00ba 10.216, de 06 de abril de 2001, a\ninterna\u00e7\u00e3o volunt\u00e1ria ou involunt\u00e1ria somente ser\u00e1 autorizada:",
        options: {
            A: "Por m\u00e9dico devidamente registrado no Conselho Regional de Medicina (CRM)\ndo Estado onde se localize o estabelecimento.",
            B: "Por consenso de Equipe Multidisciplinar do estabelecimento no qual a\ninterna\u00e7\u00e3o ser\u00e1 realizada.",
            C: "Pelo Minist\u00e9rio P\u00fablico Estadual.",
            D: "Pela Defensoria P\u00fablica.",
            E: "Pelo Respons\u00e1vel T\u00e9cnico do estabelecimento no qual a interna\u00e7\u00e3o ser\u00e1\nrealizada.",
        },
        correctAnswer: 'B',
        comment: "\u2014 Servi\u00e7os ocupacionais\nExplica\u00e7\u00e3o objetiva\nO art. 4\u00ba da Lei n\u00ba 10.216/2001 descreve os servi\u00e7os que devem compor a assist\u00eancia\nintegral durante a interna\u00e7\u00e3o:\nServi\u00e7os m\u00e9dicos\nServi\u00e7os de enfermagem\nServi\u00e7os psicol\u00f3gicos\nServi\u00e7os de assist\u00eancia social\nA lei n\u00e3o menciona servi\u00e7os ocupacionais de forma expl\u00edcita no",
    },
    {
        id: 'p2025_042',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatriada Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\na forma mais vi\u00e1vel de combater o preconceito \u00e0s pessoas com transtornos\nmentais \u00e9:",
        options: {
            A: "Dissemina\u00e7\u00e3o da informa\u00e7\u00e3o.",
            B: "Imputa\u00e7\u00e3o da condi\u00e7\u00e3o de v\u00edtimas aos pacientes.",
            C: "Oculta\u00e7\u00e3o dos diagn\u00f3sticos e tratamentos.",
            D: "Nega\u00e7\u00e3o da exist\u00eancia das doen\u00e7as mentais.",
            E: "Atribui\u00e7\u00e3o de virtudes n\u00e3o comprovadas a interven\u00e7\u00f5es n\u00e3o baseadas em\nevid\u00eancias.",
        },
        correctAnswer: 'A',
        comment: ") A qualquer tempo.\nB) Diariamente.\nC) Semanalmente.\nD) De acordo com o previsto na rotina do hospital.\nE) Conforme julgamento do m\u00e9dico assistente.\nAlternativa correta: A \u2014 A qualquer tempo\nExplica\u00e7\u00e3o objetiva\nA Lei n\u00ba 10.216/2001, em seu art. 6\u00ba, \u00a73\u00ba, estabelece que:\nO paciente tem direito \u00e0 presen\u00e7a m\u00e9dica, a qualquer tempo, para esclarecer a\nnecessidade ou n\u00e3o de sua interna\u00e7\u00e3o involunt\u00e1ria.\nPortanto, o direito \u00e9 irrestrito, n\u00e3o sendo limitado por rotina, periodicidade ou decis\u00e3o\ndo m\u00e9dico assistente.\nResposta: A) A qualquer tempo.",
    },
    {
        id: 'p2025_047',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\ncom rela\u00e7\u00e3o aos crit\u00e9rios diagn\u00f3sticos para esquizofrenia, os subtipos da doen\u00e7a\n\u2013 paranoide, desorganizado/hebefr\u00eanicoe catatonia \u2013 foram retirados tanto da CID\ncomo do DSM, sob a justifcativa de terem pouca tradu\u00e7\u00e3o para a cl\u00ednica, n\u00e3o\nindicando tratamento ou progn\u00f3stico espec\u00edfcos. Atualmente, prop\u00f5e-se agrupar\nos sintomas em dimens\u00f5es, nas quais a intensidade pode variar, n\u00e3o sendo\napenas uma quest\u00e3o de apresentar ou n\u00e3o o sintoma, mas de qu\u00e3o intenso ele \u00e9.\nAssinale a alternativa que n\u00e3o caracteriza uma das cinco dimens\u00f5es do modelo\ndimensional mais aceito.",
        options: {
            A: "Desorganiza\u00e7\u00e3o.",
            B: "Sintomas positivos.",
            C: "Sintomas negativos.",
            D: "Sintomas cognitivos.",
            E: "Sintomas afetivos.",
        },
        correctAnswer: 'A',
        comment: "\u2014 Emitir observa\u00e7\u00f5es cr\u00edticas quanto ao ambiente e \u00e0s condi\u00e7\u00f5es de\ntrabalho (sem tom ofensivo).\nJustificativa objetiva\nA Resolu\u00e7\u00e3o CFM n\u00ba 2.336/2023 lista condutas vedadas e tamb\u00e9m condutas permitidas, desde que\nn\u00e3o configurem propaganda enganosa, autopromo\u00e7\u00e3o, sensacionalismo ou infra\u00e7\u00e3o \u00e9tica.\n\u00c9 permitido ao m\u00e9dico emitir observa\u00e7\u00f5es cr\u00edticas sobre condi\u00e7\u00f5es de trabalho, desde que:\no conte\u00fado seja ver\u00eddico,\nsem ofensas a pessoas, colegas ou institui\u00e7\u00f5es,\nsem desrespeito ou exposi\u00e7\u00e3o indevida.\nIsso n\u00e3o constitui infra\u00e7\u00e3o \u00e9tica.",
    },
    {
        id: 'p2025_052',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\num dos construtos b\u00e1sicos na compreens\u00e3o do transtorno de personalidade\nantissocial \u00e9 o de tra\u00e7os de frieza e aus\u00eancia de sentimentos. Prop\u00f5e-se que tal\ncaracter\u00edstica seria o resultado de predisposi\u00e7\u00e3o gen\u00e9tica, associada a\nexperi\u00eancias negativas na primeira inf\u00e2ncia, as quais gerariam uma mudan\u00e7a no\npadr\u00e3o de resposta ao estresse, para uma resposta embotada ou atenuada a este.\nV\u00e1rios estudos de neuroimagem mostram diversas altera\u00e7\u00f5es cerebrais em sua\nassocia\u00e7\u00e3o com os sintomas do transtorno de personalidade antissocial. Assinale\na regi\u00e3o na qual h\u00e1 achados de neuroimagem associados \u00e0 difculdade de\nreconhecer emo\u00e7\u00f5es negativas nos rostos de outras pessoas.",
        options: {
            A: "Fasc\u00edculo uncinado.",
            B: "Giro fusiforme.",
            C: "C\u00f3rtex cingulado.",
            D: "Polos temporais.",
            E: "Am\u00edgdalas.",
        },
        correctAnswer: 'A',
        comment: ") A maioria dos indiv\u00edduos que desenvolvem um transtorno do jogo demonstra um padr\u00e3o de jogo com aumento gradual da\nfrequ\u00eancia, mas com estabilidade do valor apostado.\nB) Alguns pacientes em uso de medicamento dopamin\u00e9rgico (ex.: na doen\u00e7a de Parkinson) podem sentir \u00e2nsia por jogar.\nAinda que esses sintomas desapare\u00e7am com a redu\u00e7\u00e3o da dose ou retirada dos dopamin\u00e9rgicos, o diagn\u00f3stico de transtorno\ndo jogo \u00e9 indicado.\nC) Um diagn\u00f3stico de transtorno do jogo deve ser dado mesmo se o comportamento de jogo for melhor explicado por\nepis\u00f3dios man\u00edacos.\nD) O transtorno do jogo pode ter um padr\u00e3o de ocorr\u00eancia familiar, relacionado a fatores gen\u00e9ticos e ambientais.\nE) O transtorno do jogo n\u00e3o est\u00e1 associado a tentativas ou idea\u00e7\u00e3o suicida.\nP\u00e1gina 632\nO transtorno do jogo pode ter ocorr\u00eancia familiar, influenciada por fatores\ngen\u00e9ticos e ambientais.\nPor que as outras est\u00e3o erradas (DSM-5):\nA: H\u00e1 aumento progressivo da frequ\u00eancia e do valor apostado, n\u00e3o estabilidade.\nB: Quando o jogo \u00e9 induzido por dopamin\u00e9rgicos (ex.: Parkinson), n\u00e3o se deve\ndiagnosticar transtorno do jogo.\nC: Se o comportamento ocorre em epis\u00f3dio man\u00edaco, n\u00e3o recebe esse diagn\u00f3stico.\nE: O transtorno est\u00e1 associado a idea\u00e7\u00e3o e tentativas de suic\u00eddio.",
    },
    {
        id: 'p2025_081',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\no transtorno bipolar (TB) \u00e9 um transtorno mental cr\u00f4nico, que apresenta um curso\ncl\u00ednico bastante heterog\u00eaneo. Algumas caracter\u00edsticas cl\u00ednicas podem auxiliar no\ndiagn\u00f3stico diferencial, o que \u00e9 de suma import\u00e2ncia para a pr\u00e1tica cl\u00ednica,\nconsiderando que as taxas de erros no diagn\u00f3stico inicial s\u00e3o altas e que a\ndemora no diagn\u00f3stico correto est\u00e1 associada a um pior progn\u00f3stico. Em rela\u00e7\u00e3o\nao tratamento, recentes diretrizes foram estabelecidas, de acordo com o n\u00edvel de\nevid\u00eancia de cada interven\u00e7\u00e3o farmacol\u00f3gica, e o cl\u00ednico deve identifcar em qual\nfase da doen\u00e7a o paciente se encontra para ent\u00e3o decidir o melhor tratamento.\nEm especial, uma medida adjuvante ao tratamento farmacol\u00f3gico tem sido\nassociada a um melhor progn\u00f3stico. Assinale-a.",
        options: {
            A: "Psicoeduca\u00e7\u00e3o.",
            B: "Rastreio de pacientes de alto risco na popula\u00e7\u00e3o.",
            C: "Busca ativa de pacientes ambulatoriais.",
            D: "Implementa\u00e7\u00e3o de registros eletr\u00f4nicos.",
            E: "Uso de intelig\u00eancia artifcial.",
        },
        correctAnswer: 'A',
        comment: "a ci\u00eancia e o aceite por ambos da aus\u00eancia de comprova\u00e7\u00e3o da qualidade, da seguran\u00e7a e da efic\u00e1cia dos produtos\nimportados, bem como pelos eventos adversos que podem ocorrer, sendo o profissional prescritor e o paciente ou\nseu respons\u00e1vel legal totalmente respons\u00e1veis pelo uso do produto.\nB a aceita\u00e7\u00e3o de responsabilidade solid\u00e1ria por danos \u00e0 sa\u00fade individual ou coletiva e ao meio ambiente.\nC a permiss\u00e3o para entrega a terceiros, venda, doa\u00e7\u00e3o ou uso diferente do indicado.\nD a permiss\u00e3o para intermedia\u00e7\u00e3o da importa\u00e7\u00e3o por empresa farmac\u00eautica.\nE o reconhecimento, pela ANVISA, da aprova\u00e7\u00e3o por ag\u00eancias reguladoras estrangeiras.\nAlternativa correta: A\nA RDC n\u00ba 660/2022 da ANVISA estabelece que a prescri\u00e7\u00e3o m\u00e9dica e a solicita\u00e7\u00e3o de\nimporta\u00e7\u00e3o de produtos derivados de Cannabis representam:\nci\u00eancia e aceite da aus\u00eancia de comprova\u00e7\u00e3o de qualidade, seguran\u00e7a e efic\u00e1cia,\nresponsabiliza\u00e7\u00e3o do prescritor e do paciente ou respons\u00e1vel,\nci\u00eancia dos poss\u00edveis eventos adversos,\ne responsabilidade integral pelo uso do produto.\nIsso est\u00e1 descrito de forma expl\u00edcita no regulamento, que enfatiza que ANVISA apenas\nautoriza a importa\u00e7\u00e3o, n\u00e3o garantindo qualidade, seguran\u00e7a ou efic\u00e1cia \u2014 e n\u00e3o\nassumindo responsabilidade sobre os efeitos decorrentes do uso.\nPor isso, a alternativa A reproduz exatamente o que a norma determina",
    },
    {
        id: 'p2025_083',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a Refer\u00eancia ASSOCIA\u00c7\u00c3O PSIQUI\u00c1TRICA AMERICANA (APA).\nManual Diagn\u00f3stico e Estat\u00edstico de Transtornos Mentais. 5. ed. (DSM-5). Artmed,\n2014, a forma de possess\u00e3o do transtorno dissociativo de identidade manifestase, em geral, como comportamentos que surgem como se um \u201cesp\u00edrito\u201d, um ser\nsobrenatural ou uma entidade externa tivesse assumido o controle, de tal forma\nque o indiv\u00edduo come\u00e7a a falar e agir de maneira claramente diferente. Por\nexemplo, o comportamento de uma pessoa pode fazer parecer que sua identidade\nfoi substitu\u00edda pelo \u201cfantasma\u201d de uma menina que cometeu suic\u00eddio na mesma\ncomunidade anos atr\u00e1s, falando e agindo como se ela ainda estivesse viva. Ou a\npessoa pode ser \u201cpossu\u00edda\u201d por um dem\u00f4nio ou divindade, resultando em uma\naltera\u00e7\u00e3o profunda, e exigindo que a pr\u00f3pria pessoa ou um familiar seu seja\npunido por uma a\u00e7\u00e3o do passado. Muitos aspectos do transtorno dissociativo de\nidentidade podem ser in\ufb02uenciados pela forma\u00e7\u00e3o cultural do indiv\u00edduo. Pessoas\ncom esse transtorno podem se apresentar com sintomas neurol\u00f3gicos\nproeminentes clinicamente inexplic\u00e1veis, como convuls\u00f5es n\u00e3o epil\u00e9pticas,\nparalisias ou perda sensorial, em contextos culturais nos quais tais sintomas s\u00e3o\ncomuns. Da mesma maneira, em contextos nos quais a possess\u00e3o \u00e9 comum (por\nexemplo, \u00e1reas rurais em pa\u00edses em desenvolvimento, entre determinados grupos\nreligiosos nos Estados Unidos e na Europa), as identidades fragmentadas podem\nadotar a forma de esp\u00edritos, divindades, dem\u00f4nios, animais ou fguras m\u00edticas de\npossess\u00e3o. A acultura\u00e7\u00e3o ou o contato intercultural prolongado podem modelar\nas caracter\u00edsticas das outras identidades (por exemplo, identidades na \u00cdndia\npodem falar exclusivamente ingl\u00eas e usar roupas ocidentais).\nO diagn\u00f3stico de transtorno dissociativo de identidade na forma de possess\u00e3o\npode ser exclu\u00eddo em uma das seguintes hip\u00f3teses. Assinale-a.",
        options: {
            A: "H\u00e1 sofrimento ou preju\u00edzo clinicamente signifcativos.",
            B: "Ocorrem per\u00edodos mais sutis de altera\u00e7\u00e3o da identidade.",
            C: "H\u00e1 presen\u00e7a de dois ou mais estados de personalidade distintos.",
            D: "A perturba\u00e7\u00e3o \u00e9 parte de pr\u00e1ticas espirituais ou culturais amplamente aceitas.",
            E: "As identidades que surgem durante o transtorno apresentam-se de forma\nrecorrente, s\u00e3o involunt\u00e1rias e indesej\u00e1veis.",
        },
        correctAnswer: 'A',
        comment: "\u2014 \u201cO objetivo \u00e9 o abandono ou substitui\u00e7\u00e3o das\nclassifica\u00e7\u00f5es categoriais.\u201d\nEssa n\u00e3o \u00e9 uma premissa do RDoC.\nPor qu\u00ea?\nO RDoC n\u00e3o pretende substituir o DSM/CID nem abolir classifica\u00e7\u00f5es categoriais.\nSeu objetivo \u00e9 complementar esses sistemas, oferecendo um modelo dimensional e\nneurobiol\u00f3gico para pesquisa \u2014 n\u00e3o fazer mudan\u00e7as diretas na pr\u00e1tica cl\u00ednica imediata.",
    },
    {
        id: 'p2025_086',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia AMERICAN PSYCHIATRIC ASSOCIATION. Manual\nDiagn\u00f3stico e Estat\u00edstico de Transtornos Mentais. 5. ed. (DSM-5). Artmed, 2014, o\nin\u00edcio do transtorno disf\u00f3rico pr\u00e9-menstrual pode ocorrer a qualquer momento\nap\u00f3s a menarca. A incid\u00eancia de casos novos durante um per\u00edodo de\nacompanhamento de 40 meses \u00e9 de 2,5% (intervalo deconfan\u00e7a [IC] 95% = 1,7-\n3,7). Eles cessam ap\u00f3s a menopausa, embora a reposi\u00e7\u00e3o hormonal c\u00edclica possa\ndesencadear nova manifesta\u00e7\u00e3o dos sintomas.\nH\u00e1 relatos de que muitas mulheres, quando se aproximam da menopausa,\nreferem",
        options: {
            A: "melhora nos sintomas",
            B: "mudan\u00e7a sutil no tipo de sintomas.",
            C: "interrup\u00e7\u00e3o dos sintomas",
            D: "piora nos sintomas.",
            E: "mudan\u00e7a signifcativa no tipo dos sintomas.",
        },
        correctAnswer: 'A',
        comment: "\u2014 facial e glossofar\u00edngeo\nParageusia (altera\u00e7\u00e3o qualitativa do paladar) e alucina\u00e7\u00f5es gustativas est\u00e3o\nrelacionadas aos nervos respons\u00e1veis pela gusta\u00e7\u00e3o:\nFacial (VII par): gusta\u00e7\u00e3o nos 2/3 anteriores da l\u00edngua.\nGlossofar\u00edngeo (IX par): gusta\u00e7\u00e3o no ter\u00e7o posterior da l\u00edngua.\nAmbos s\u00e3o diretamente envolvidos em dist\u00farbios do paladar, como descrito no Tratado\nde Psiquiatria da ABP (2022).",
    },
    {
        id: 'p2025_088',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\nna implementa\u00e7\u00e3o de um esquema de tratamento antidepressivo, assinale um\nfator, relacionado ao paciente, a ser levado em considera\u00e7\u00e3o na escolha de um\nantidepressivo.",
        options: {
            A: "Disponibilidade.",
            B: "Tolerabilidade comparativa.",
            C: "Efeitos colaterais pr\u00e9vios.",
            D: "Potenciais intera\u00e7\u00f5es medicamentosas em geral.",
            E: "Potenciais intera\u00e7\u00f5es com outras medica\u00e7\u00f5es em uso pelo paciente.\nP\u00e1gina 733 Fatores do paciente Caracter\u00edsticas cl\u00ednicas e dimens\u00f5es\nComorbidades cl\u00ednicas e psiqui\u00e1tricas Resposta pr\u00e9via Efeitos colaterais pr\u00e9vios\nPrefer\u00eancia do paciente Hist\u00f3ria familiar de resposta",
        },
        correctAnswer: 'A',
        comment: "A resolu\u00e7\u00e3o de sintomas pode ser mais r\u00e1pida em pacientes com fun\u00e7\u00e3o cognitiva pr\u00e9via deficiente,\ndiagn\u00f3stico incorreto ou incompleto de fatores contribuintes, e doen\u00e7as cerebrais estruturais tratadas\ncom grandes doses de medicamentos psicoativos.\nB Existe o risco de o paciente nunca mais retornar ao seu n\u00edvel anterior de funcionamento\ncognitivo.\nC O desfecho mais prov\u00e1vel em tr\u00eas meses \u00e9 a morte.\nD A idade do paciente n\u00e3o influencia o progn\u00f3stico.\nE N\u00e3o est\u00e1 associado \u00e0 admiss\u00e3o em institui\u00e7\u00f5es de longa perman\u00eancia.\nP\u00e1gina 1391\nJustificativa objetiva\nO Tratado destaca que o delirium tem progn\u00f3stico muitas vezes desfavor\u00e1vel,\nmesmo ap\u00f3s a resolu\u00e7\u00e3o aparente do quadro agudo. Entre as consequ\u00eancias descritas:\nrisco aumentado de decl\u00ednio cognitivo persistente,\nmaior probabilidade de n\u00e3o retorno ao n\u00edvel basal de funcionamento,\nassocia\u00e7\u00e3o com maior mortalidade, institucionaliza\u00e7\u00e3o e perda funcional.\nPor isso, entre as alternativas, B \u00e9 a \u00fanica que descreve corretamente um aspecto\nverdadeiro e clinicamente relevante do progn\u00f3stico.",
    },
    {
        id: 'p2025_089',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\na humanidade vem fazendo uso emp\u00edrico de subst\u00e2ncias psicoativas desde os\nseus remotos prim\u00f3rdios para fns recreativos, espirituais e terap\u00eauticos. A\npsicofarmacologia cient\u00edfca, por\u00e9m, \u00e9 flha direta da qu\u00edmica moderna, e s\u00f3 viu a\nluz do sol na segunda metade do s\u00e9culo XIX, inaugurando a pr\u00e9-hist\u00f3ria da\nmoderna terap\u00eautica psiqui\u00e1trica. Mesmo assim, o arsenal terap\u00eautico das\ninstitui\u00e7\u00f5es asilares da segunda metade do s\u00e9culo XIX era bastante restrito,\nlimitando-se a subst\u00e2ncias sedativas com baixa margem de seguran\u00e7a, como\nhidrato cloral, paralde\u00eddo e opi\u00e1ceos e, posteriormente, os barbituratos.\nTratamentos farmacol\u00f3gicos seletivos para quadros psic\u00f3ticos, ansiedade,\ndepress\u00e3o e mania eram, ent\u00e3o, pouco mais que distantes miragens. O evento\nque logrou transformar uma dessas miragens em realidade palp\u00e1vel, marcando,\nassim, o in\u00edcio da chamada Era de Ouro da psicofarmacologia, foi a comprova\u00e7\u00e3o\ndas propriedades deliriol\u00edticas do composto Rh\u00f4ne-Poulenc 4560, por Deniker e\nDelay, no Centre Hospitalier Sainte-Anne, em 1952. Esse composto, que se\ntornaria conhecido sob o nome clorpromazina, foi sintetizado por Paul\nCharpentier a partir do n\u00facleo fenotiaz\u00ednico originalmente empregado naprodu\u00e7\u00e3o\nde corantes org\u00e2nicos. Apenas quatro anos depois, quatro milh\u00f5es de norte-\namericanos estavam sendo medicados com esse f\u00e1rmaco, um primeiro passo que\npropiciaria a mudan\u00e7a irrevers\u00edvel do cen\u00e1rio do tratamento dos quadros\npsic\u00f3ticos do meio asilar para o comunit\u00e1rio. A manipula\u00e7\u00e3o qu\u00edmica do n\u00facleo\nfenotiaz\u00ednico levou \u00e0 cria\u00e7\u00e3o de v\u00e1rias mol\u00e9culas om propriedades compar\u00e1veis,\ncomo a tioridazina, a \ufb02ufenazina e a tri\ufb02uoperazina. Outros compostos, como a\nbutirofenona haloperidol, desenvolvida por Paul Jansen em 1958, na B\u00e9lgica,\nrevelaram-se igualmente efetivos.\nO campo das neuroci\u00eancias tamb\u00e9m foi radicalmente afetado pelos frutos da Era\nde Ouro da psicofarmacologia. As pesquisas de Arvid Carlsson, no fnal dos anos\n1950 e no in\u00edcio dos anos1960, que lhe proporcionariam o Pr\u00eamio Nobel de\nMedicina e Fisiologia em 2000, juntamente com Paul Greengard e Eric Kandel,\ndemonstraram que a clorpromazina exercia seus efeitos antipsic\u00f3ticos por meio\ndo bloqueio da a\u00e7\u00e3o de um neurotransmissor no SNC. Assinale-o.",
        options: {
            A: "Norepinefrina.",
            B: "Glutamato.",
            C: "Serotonina.",
            D: "Dopamina.",
            E: "GABA.",
        },
        correctAnswer: 'E',
        comment: "\u2014 Valproato\nExplica\u00e7\u00e3o objetiva\nO valproato inibe a ep\u00f3xido-hidrolase, enzima respons\u00e1vel pela metaboliza\u00e7\u00e3o do carbamazepina-10,11-\nep\u00f3xido, o principal metab\u00f3lito ativo da carbamazepina.\nResultado: aumento significativo do n\u00edvel plasm\u00e1tico do ep\u00f3xido \u2192 maior risco de toxicidade (tontura,\nataxia, diplopia, seda\u00e7\u00e3o).\nPor que as demais est\u00e3o incorretas?\nA) Pregabalina \u2192 sem intera\u00e7\u00e3o metab\u00f3lica relevante com carbamazepina.\nB) Lamotrigina \u2192 pode ter n\u00edveis reduzidos pela carbamazepina (indu\u00e7\u00e3o enzim\u00e1tica), n\u00e3o aumentar o\nep\u00f3xido.\nC) Quetiapina \u2192 metabolizada por CYP3A4, sendo reduzida pela carbamazepina; n\u00e3o afeta o ep\u00f3xido.\nD) Aripiprazol \u2192 tamb\u00e9m reduzido pela indu\u00e7\u00e3o da carbamazepina; n\u00e3o aumenta metab\u00f3lito.",
    },
    {
        id: 'p2025_090',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia AMERICAN PSYCHIATRIC. Manual Diagn\u00f3stico e\nEstat\u00edstico de Transtornos Mentais. 5. ed. (DSM-5). Artmed, 2014, e em rela\u00e7\u00e3o\naos dom\u00ednios cognitivos, h\u00e1 uma defni\u00e7\u00e3o de trabalho para cada um dos\ndom\u00ednios principais e s\u00e3o citados exemplos de sintomas ou observa\u00e7\u00f5es relativas\naos preju\u00edzos a eles relacionados em atividades cotidianas e exemplos de\navalia\u00e7\u00f5es. Os dom\u00ednios principais s\u00e3o separados em:\n- Perceptomotor (inclui habilidades abrangidas por termos como percep\u00e7\u00e3o\nvisual, visuoconstrutiva, perceptomotora, pr\u00e1xis e gnosia).\n- Cogni\u00e7\u00e3o social (reconhecimento de emo\u00e7\u00f5es, teoria da mente).\n- Aprendizagem e mem\u00f3ria (mem\u00f3ria imediata, mem\u00f3ria recente [incluindo\nrecorda\u00e7\u00e3o livre, recorda\u00e7\u00e3o por pistas e mem\u00f3ria de reconhecimento]; mem\u00f3ria\nde muito longo prazo[sem\u00e2ntica, autobiogr\u00e1fca], aprendizagem impl\u00edcita).\n- Linguagem (linguagem expressiva [inclui nomea\u00e7\u00e3o, encontrar palavras, \ufb02u\u00eancia,\ngram\u00e1tica e sintaxe] e linguagem receptiva).\n- Aten\u00e7\u00e3o complexa (aten\u00e7\u00e3o sustentada, aten\u00e7\u00e3o dividida, aten\u00e7\u00e3o seletiva,\nvelocidade de processamento).\n- Fun\u00e7\u00e3o executiva (planejamento, tomada de decis\u00e3o, mem\u00f3ria de trabalho,\nresposta a feedback/corre\u00e7\u00e3o de erros, substituir h\u00e1bitos/inibi\u00e7\u00e3o, \ufb02exibilidade\nmental).\nA descri\u00e7\u00e3o a seguir representa exemplos de sintomas ou observa\u00e7\u00f5es na forma\nleve de altera\u00e7\u00e3o de um desses dom\u00ednios: \u201cTarefas normais levam mais tempo do\nque anteriormente. Passa a cometer erros em tarefas rotineiras; acha que o\ntrabalho necessita ser conferido de novo mais vezes do que anteriormente. Pensar\n\u00e9 mais f\u00e1cil quando n\u00e3o \u00e9 concomitante com outras coisas (r\u00e1dio, TV, outras\nconversas, telefone celular, dirigir).\u201d\nA qual dom\u00ednio essa descri\u00e7\u00e3o se refere?",
        options: {
            A: "Fun\u00e7\u00e3o executiva.",
            B: "Perceptomotor.",
            C: "Cogni\u00e7\u00e3o social.",
            D: "Aten\u00e7\u00e3o complexa.",
            E: "Aprendizagem e mem\u00f3ria.",
        },
        correctAnswer: 'B',
        comment: "\u2014 Dor na garganta\nExplica\u00e7\u00e3o objetiva\nNa avalia\u00e7\u00e3o de rash induzido por lamotrigina, sinais sist\u00eamicos s\u00e3o os marcadores mais importantes\nde gravidade e poss\u00edvel evolu\u00e7\u00e3o para:\nS\u00edndrome de Stevens-Johnson (SSJ)\nNecr\u00f3lise epid\u00e9rmica t\u00f3xica (NET)\nEntre esses sinais, destacam-se:\nFebre\nMal-estar\nDor na garganta / odinofagia \u2192 indica poss\u00edvel comprometimento de mucosas, achado precoce\nnas rea\u00e7\u00f5es cut\u00e2neas graves.",
    },
    {
        id: 'p2025_091',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia AMERICAN PSYCHIATRIC ASSOCIATION. Manual\nDiagn\u00f3stico e Estat\u00edstico de Transtornos Mentais. 5. ed. (DSM-5). Artmed, 2014, a\ncaracter\u00edstica essencial da autoles\u00e3o n\u00e3o suicida \u00e9 o comportamento repetido do\npr\u00f3prio indiv\u00edduo de in\ufb02igir les\u00f5es superfciais, embora dolorosas, \u00e0 superf\u00edcie do\nseu corpo. Em alguns casos, a les\u00e3o \u00e9 concebida como uma autopuni\u00e7\u00e3o\nmerecida. O indiv\u00edduo frequentemente relatar\u00e1 uma sensa\u00e7\u00e3o imediata de al\u00edvio\nque ocorre durante o processo.\nQuando o comportamento ocorre de forma frequente, pode estar associado a um\nsenso de urg\u00eancia e fssura, com o padr\u00e3o comportamental resultante lembrando\na adi\u00e7\u00e3o. Os ferimentos in\ufb02igidos podem se tornar mais profundos e mais\nnumerosos. A les\u00e3o \u00e9 mais frequentemente in\ufb02igida com uma faca, agulha,\nl\u00e2mina ou outro objeto afado. Locais comuns para les\u00e3o incluem a \u00e1rea frontal\ndas coxas e o lado dorsal do antebra\u00e7o. Uma \u00fanica sess\u00e3o de les\u00e3o pode envolver\numa s\u00e9rie de cortes paralelos superfciais \u2013 separados por 1 ou 2 cent\u00edmetros \u2013 em\num local vis\u00edvel ou acess\u00edvel. Os cortes resultantes com frequ\u00eancia ir\u00e3o sangrar e\neventualmente deixar\u00e3o um padr\u00e3o de cicatrizes caracter\u00edstico. Outros m\u00e9todos\nutilizados incluem fncar uma agulha ou faca de ponta afada em uma \u00e1rea, em\ngeral na parte superior do bra\u00e7o; in\ufb02igir uma queimadura superfcial com a ponta\nde um cigarro aceso; ou queimar a pele esfregando repetidamente uma borracha.\nO envolvimento em autoles\u00e3o n\u00e3o suicida com m\u00faltiplos m\u00e9todos est\u00e1 associado\na psicopatologia mais grave, incluindo tentativas de suic\u00eddio.\nA grande maioria dos indiv\u00edduos que se engajam em autoles\u00e3o n\u00e3o suicida n\u00e3o\nbusca atendimento cl\u00ednico. N\u00e3o se sabe se isso re\ufb02ete a frequ\u00eancia do\nenvolvimento no transtorno, porque o relato preciso \u00e9 visto como estigmatizante\nou porque os comportamentos s\u00e3o experimentados de forma positiva pelo\nindiv\u00edduo que se engaja neles, que n\u00e3o est\u00e1 motivado para receber tratamento.\nCrian\u00e7as pequenas podem fazer experi\u00eancias com esses comportamentos, mas\nn\u00e3o sentir um al\u00edvio. Nesses casos, os jovens costumam relatar que o\nprocedimento \u00e9 doloroso ou causa sofrimento e podem, ent\u00e3o, descontinuar a\npr\u00e1tica. A autoles\u00e3o n\u00e3o suicida foi, por muito tempo, considerada um \u201csintoma\u201d\ndo transtorno da personalidade borderline, embora avalia\u00e7\u00f5es cl\u00ednicas\nabrangentes tenham encontrado que a maioria dos indiv\u00edduos com autoles\u00e3o n\u00e3o\nsuicida tem sintomas que tamb\u00e9m preenchem crit\u00e9rios para outros diagn\u00f3sticos,\ncom os transtornos alimentares e transtornos por uso de subst\u00e2ncias sendo\nespecialmente comuns. Historicamente, a autoles\u00e3o n\u00e3o suicida foi considerada\npatognom\u00f4nica do transtorno da personalidade borderline. Ambas as condi\u00e7\u00f5es\nest\u00e3o associadas a v\u00e1rios outros diagn\u00f3sticos. Embora com frequ\u00eancia associado,\no transtorno da personalidade borderline n\u00e3o \u00e9 invariavelmente encontrado em\nindiv\u00edduos com autoles\u00e3o n\u00e3o suicida. As duas condi\u00e7\u00f5es diferem em v\u00e1rios\naspectos. Indiv\u00edduos com transtorno da personalidade borderline com frequ\u00eancia\nmanifestam comportamentos perturbados agressivos e hostis, enquanto a\nautoles\u00e3o n\u00e3o suicida est\u00e1 mais associada a fases de proximidade,\ncomportamentos colaborativos e relacionamentos positivos. Em um n\u00edvel mais\nfundamental, existem diferen\u00e7as no envolvimento de sistemas diferentes de\nneurotransmissores, mas estas n\u00e3o ser\u00e3o aparentes ao exame cl\u00ednico. Assinale\numa caracter\u00edstica do transtorno do comportamento suicida.",
        options: {
            A: "Objetivo declarado do comportamento como desejo de morrer. Dependendo\ndas circunst\u00e2ncias, os indiv\u00edduos podem fazer relatos por conveni\u00eancia, e v\u00e1rios\nestudos relatam altas taxas de declara\u00e7\u00e3o de falsas inten\u00e7\u00f5es.",
            B: "No \u00faltimo ano, o indiv\u00edduo se engajou, em cinco ou mais dias, em dano\nintencional auto in\ufb02igido \u00e0 superf\u00edcie do seu corpo, provavelmente induzindo\nsangramento, contus\u00e3o ou dor.",
            C: "O comportamento visa experimentar al\u00edvio, resolver uma difculdade\ninterpessoal ou induzir um estado de sentimento positivo.",
            D: "O al\u00edvio ou resposta desejada \u00e9 experimentado durante ou logo ap\u00f3s a\nautoles\u00e3o, e o indiv\u00edduo pode exibir padr\u00f5es de comportamento que sugerem uma\ndepend\u00eancia em repetidamente se envolver neles.",
            E: "Antes do engajamento no ato, um per\u00edodo de preocupa\u00e7\u00e3o com o\ncomportamento pretendido, que \u00e9 dif\u00edcil de controlar.",
        },
        correctAnswer: 'D',
        comment: "\u2014 Modifica\u00e7\u00f5es qu\u00edmicas das histonas\nExplica\u00e7\u00e3o objetiva\nMecanismos epigen\u00e9ticos s\u00e3o altera\u00e7\u00f5es funcionais que modificam a express\u00e3o g\u00eanica\nsem alterar a sequ\u00eancia do DNA.\nOs principais mecanismos epigen\u00e9ticos s\u00e3o:\nMetila\u00e7\u00e3o do DNA\nModifica\u00e7\u00f5es qu\u00edmicas das histonas (acetila\u00e7\u00e3o, metila\u00e7\u00e3o, fosforila\u00e7\u00e3o etc.)\nRegula\u00e7\u00e3o por microRNAs\nPortanto, modifica\u00e7\u00f5es qu\u00edmicas das histonas \u00e9 a \u00fanica alternativa que descreve um\nmecanismo epigen\u00e9tico.",
    },
    {
        id: 'p2025_094',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\na busca por biomarcadores plasm\u00e1ticos da Doen\u00e7a de Alzheimer (DA) vem sendo\num campo de aten\u00e7\u00e3o nas pesquisas na \u00e1rea. A realiza\u00e7\u00e3o de diagn\u00f3stico por\nessa via traria benef\u00edcios signifcativos, resultando em maior acessibilidade e\nmenores custos, com grande impacto n\u00e3o apenas na pesquisa cl\u00ednica, mas\ntamb\u00e9m na sa\u00fade p\u00fablica. Essa modalidade de biomarcadores ainda n\u00e3o\napresenta padroniza\u00e7\u00e3o para utiliza\u00e7\u00e3o cl\u00ednica, mas h\u00e1 um crescente interesse\ncient\u00edfco na dissemina\u00e7\u00e3o de seu uso. Assinale a alternativa que inclui um dos\nbiomarcadores plasm\u00e1ticos com melhores resultados na estimativa do processo\npatol\u00f3gico da DA.",
        options: {
            A: "Raz\u00e3o \u03b2A42/\u03b2A40.",
            B: "Prote\u00edna tau (p-tau).",
            C: "Alipoliprote\u00edna E (Apo E).",
            D: "Pept\u00eddeo beta-amiloide (\u00dfA).",
            E: "Prote\u00edna precursora de amiloide (APP).",
        },
        correctAnswer: 'E',
        comment: "\u2014 alucina\u00e7\u00f5es visuais amea\u00e7adoras.\nExplica\u00e7\u00e3o objetiva\nSintomas de primeira ordem de Kurt Schneider \u2014 considerados altamente sugestivos de\nesquizofrenia \u2014 incluem:\nVozes comentadoras (A)\nVozes dialogando entre si\nViv\u00eancias de influ\u00eancia ou controle externo (B)\nRoubo, inser\u00e7\u00e3o ou transmiss\u00e3o do pensamento (C)\nPercep\u00e7\u00e3o delirante (D)\nEsses sintomas refletem altera\u00e7\u00f5es do Ichst\u00f6rungen (dist\u00farbios da viv\u00eancia do eu), altamente t\u00edpicos.",
    },
    {
        id: 'p2025_097',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatriada Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\na abordagem medicamentosa \u00e9 a base atual do tratamento das depress\u00f5es\nmoderadas a graves. Quando uma tentativa com antidepressivo apresenta\nresposta parcial ou aus\u00eancia de resposta, considera-sequatro alternativas a\nserem implementadas. Assinale a alternativa compat\u00edvel com a defni\u00e7\u00e3o:\n\u201cmedicamentos antidepressivos possuem uma janela terap\u00eautica com doses\nm\u00ednimas e m\u00e1ximas, al\u00e9m de uma janela de efeitos colaterais. A obten\u00e7\u00e3o de\ndoses terap\u00eauticas livres de efeitos colaterais signifcativos \u00e9 uma habilidade a ser\ndesenvolvida pelo profssional e personalizada para cada paciente. Para cada\ndose prescrita, \u00e9 importante aguardar um tempo m\u00ednimo (em torno de tr\u00eas a seis\nsemanas) para obter o efeito. Um subgrupo de pacientes pode precisar de tempo\nmais prolongado, que pode chegar at\u00e9 12semanas. O aumento da dose e a\ndilata\u00e7\u00e3o do tempo de uso s\u00e3o preferencialmente utilizadas quando existe uma\nresposta parcial, o medicamento est\u00e1 sendo bem tolerado e h\u00e1 ainda espa\u00e7o para\nessas medidas.\u201d.",
        options: {
            A: "Troca.",
            B: "Otimiza\u00e7\u00e3o.",
            C: "Potencializa\u00e7\u00e3o.",
            D: "Combina\u00e7\u00e3o.",
            E: "Reavalia\u00e7\u00e3o.",
        },
        correctAnswer: 'A',
        comment: "\u00c9 indicada nos epis\u00f3dios de depress\u00e3o com resposta parcial aos antidepressivos.\nB Apresenta tamanho de efeito menor em rela\u00e7\u00e3o aos estimulantes.\nC \u00c9 indicada na hipotens\u00e3o ortost\u00e1tica neurog\u00eanica.\nD N\u00e3o pode ser associada aos estimulantes.\nE Possui meia-vida longa.\nP\u00e1gina 1310\nAlternativa correta: B \u2014 Apresenta tamanho de efeito menor em rela\u00e7\u00e3o aos estimulantes.\nJustificativa objetiva\nA atomoxetina \u00e9 eficaz, mas possui tamanho de efeito inferior aos estimulantes (metilfenidato e anfetaminas), que\nseguem como primeira linha no TDAH.\nIsso \u00e9 amplamente confirmado em metan\u00e1lises e \u00e9 explicitado no Tratado.\nPor que as outras est\u00e3o incorretas?\nA) N\u00e3o \u00e9 indicada como estrat\u00e9gia para epis\u00f3dios depressivos com resposta parcial. N\u00e3o \u00e9 antidepressivo.\nC) N\u00e3o \u00e9 indicada para hipotens\u00e3o ortost\u00e1tica; pelo contr\u00e1rio, aumenta PA e FC.\nD) Pode ser associada a estimulantes em situa\u00e7\u00f5es espec\u00edficas, embora n\u00e3o seja rotina.\nE) A meia-vida da atomoxetina n\u00e3o \u00e9 longa; varia conforme metaboliza\u00e7\u00e3o pelo CYP2D6 (curta em metabolizadores r\u00e1pidos;\nprolongada apenas em metabolizadores lentos).",
    },
    {
        id: 'p2025_098',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\nh\u00e1 uma modalidade de tratamento estruturada especifcamente para pacientes\ncom transtorno da personalidade borderline, embora tenha sido recentemente\nutilizado em outras popula\u00e7\u00f5es. Essa modalidade parte da premissa de que a\ndesregula\u00e7\u00e3o emocional levaria a distor\u00e7\u00f5es cognitivas e comportamentos\ndisfuncionais. Divide elementos com sistemas psicodin\u00e2micos, centrada no\ncliente, Gestalt e estrat\u00e9gias paradoxais, mindfulness e a flosofa oriental. A que\nforma de psicoterapia esse texto se refere?",
        options: {
            A: "Terapia do esquema.",
            B: "Terapia cognitiva processual.",
            C: "Terapia comportamental dial\u00e9tica.",
            D: "Psicoterapia interpessoal.",
            E: "Terapia de aceita\u00e7\u00e3o e compromisso.",
        },
        correctAnswer: 'E',
        comment: "\u2014 Regress\u00e3o \u00e0 m\u00e9dia.\nResumo objetivo\nO fen\u00f4meno descrito \u2014 melhora aparente ap\u00f3s uma interven\u00e7\u00e3o apenas porque a\nmedi\u00e7\u00e3o inicial ocorreu em um ponto de extrema gravidade, seguido de retorno natural\ndos sintomas ao seu valor habitual \u2014 corresponde exatamente \u00e0 regress\u00e3o \u00e0 m\u00e9dia.\nEsse efeito \u00e9 um problema cl\u00e1ssico dos estudos \u201cantes e depois\u201d, pois cria falsa\nimpress\u00e3o de efic\u00e1cia quando n\u00e3o h\u00e1 grupo controle.",
    },
    {
        id: 'p2025_099',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\no hipot\u00e1lamo faz parte do dienc\u00e9falo, apresenta uma complexa estrutura\nanat\u00f4mica e pouca defni\u00e7\u00e3o de seus n\u00facleos, de tamanho reduzido. De maneira\ngeral, as manifesta\u00e7\u00f5es parassimp\u00e1ticas est\u00e3o relacionadas como hipot\u00e1lamo\nanterior, enquanto o hipot\u00e1lamo posterior coordena as fun\u00e7\u00f5es simp\u00e1ticas. O\nhipot\u00e1lamo tem como principais fun\u00e7\u00f5es a manuten\u00e7\u00e3o da homeostasia (o\ncontrole sobre o sistema nervoso aut\u00f4nomo, incluindo a termorregula\u00e7\u00e3o, a\nregula\u00e7\u00e3o da sede, a regula\u00e7\u00e3o da ingest\u00e3o de alimentos, o rel\u00f3gio biol\u00f3gico, o\ncomportamento sexual e a reprodu\u00e7\u00e3o, al\u00e9m da regula\u00e7\u00e3o do comportamento). O\nhipot\u00e1lamo integra informa\u00e7\u00e3o de diversas \u00e1reas em resposta avariados\nest\u00edmulos, como a luz, que regula o ciclo circadiano. Os principais sintomas da\nles\u00e3o do hipot\u00e1lamo podem estar relacionados a agressividade, estresse,\nhipotermia, hipersonia, letargia, automutila\u00e7\u00e3o, ganho ou perda de peso, aumento\nou diminui\u00e7\u00e3o do desejo sexual. Altera\u00e7\u00f5es funcionais dessa estrutura j\u00e1 foram\nrelacionadas a depress\u00e3o, transtorno bipolar, esquizofrenia e transtorno de\nestresse p\u00f3s-traum\u00e1tico.\nOs neur\u00f4nios presentes na regi\u00e3o tuberal, logo acima da hip\u00f3fse, produzem uma\nsubst\u00e2ncia que \u00e9 liberada no sistema hipofs\u00e1rio e est\u00e1 relacionada a efeitos\nadversos de alguns psicof\u00e1rmacos que atuam sobre os seus receptores na\nhip\u00f3fse anterior. Assinale-a.",
        options: {
            A: "GABA.",
            B: "Serotonina.",
            C: "Dopamina.",
            D: "Norepinefrina.",
            E: "Horm\u00f4nio Adrenocorticotr\u00f3fco (ACTH).",
        },
        correctAnswer: 'E',
        comment: "\u2014 2D6 e 2C19\nExplica\u00e7\u00e3o objetiva\nAs diretrizes internacionais de farmacogen\u00e9tica (como CPIC e DPWG) utilizam\npolimorfismos nos genes CYP2D6 e CYP2C19 para orientar ajustes de dose de\ndiversos antidepressivos (ISRSs e IRSNs principalmente).\nEsses genes influenciam metaboliza\u00e7\u00e3o (farmacocin\u00e9tica), n\u00e3o o efeito\nfarmacodin\u00e2mico.\nPor isso, E \u00e9 a resposta correta.",
    },
    {
        id: 'p2025_100',
        theme: 'geral',
        subtheme: 'Geral',
        difficulty: 2,
        statement: "De acordo com a refer\u00eancia NARDI, A. E.; SILVA, A. G.; QUEVEDO, J. (org.). Tratado\nde Psiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022,\no princ\u00edpio \u00e9tico que visa a garantir distribui\u00e7\u00e3o de recursos equilibrada e que\npossa abranger, de maneira efcaz, o maior n\u00famero de pessoas e que pressup\u00f5e\natua\u00e7\u00e3o m\u00e9dica imparcial, evitando que aspectos econ\u00f4micos, sociais, culturais,\nreligiosos ou outros interfram na rela\u00e7\u00e3o m\u00e9dico-paciente \u00e9 denominado:",
        options: {
            A: "N\u00e3o \u00e9 indicada como estrat\u00e9gia para epis\u00f3dios depressivos com resposta parcial. N\u00e3o \u00e9 antidepressivo.",
            B: "Lamotrigina \u2192 pode ter n\u00edveis reduzidos pela carbamazepina (indu\u00e7\u00e3o enzim\u00e1tica), n\u00e3o aumentar o\nep\u00f3xido.",
            C: "N\u00e3o \u00e9 indicada para hipotens\u00e3o ortost\u00e1tica; pelo contr\u00e1rio, aumenta PA e FC.",
            D: "Pode ser associada a estimulantes em situa\u00e7\u00f5es espec\u00edficas, embora n\u00e3o seja rotina.",
            E: "A meia-vida da atomoxetina n\u00e3o \u00e9 longa; varia conforme metaboliza\u00e7\u00e3o pelo CYP2D6 (curta em metabolizadores r\u00e1pidos;\nprolongada apenas em metabolizadores lentos).\n98\nDe acordo com a refer\u00eancia Nardi, A. E.; Silva, A. G.; Quevedo, J. (org.). Tratado de Psiquiatria da\nAssocia\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022, h\u00e1 um fen\u00f4meno estat\u00edstico capaz de\nfazer com que uma varia\u00e7\u00e3o natural em dados repetidos pare\u00e7a uma mudan\u00e7a real produzida por uma\ninterven\u00e7\u00e3o. Em uma situa\u00e7\u00e3o hipot\u00e9tica na qual a gravidade dos sintomas depressivos de uma\npaciente \u00e9 avaliada imediatamente antes do in\u00edcio do tratamento e, nas duas avalia\u00e7\u00f5es subsequentes,\nobserva-se uma queda na intensidade dos sintomas, pode parecer que o medicamento foi respons\u00e1vel\npela melhora. No entanto, se fosse poss\u00edvel conhecer o curso natural dos sintomas dessa paciente,\nseria plaus\u00edvel que a interven\u00e7\u00e3o medicamentosa n\u00e3o tivesse exercido qualquer efeito. Os sintomas\napresentam um padr\u00e3o natural de oscila\u00e7\u00f5es, com altos e baixos em torno de um ponto central. Como\n\u00e9 comum que o paciente busque ajuda psiqui\u00e1trica justamente quando os sintomas atingem maior\nintensidade, ap\u00f3s certo tempo esses sintomas tendem a retornar ao ponto m\u00e9dio, produzindo uma\nfalsa impress\u00e3o de efic\u00e1cia terap\u00eautica. Esse \u00e9 um dos principais problemas de estudos experimentais\nque utilizam compara\u00e7\u00f5es \u201cantes e depois\u201d.\nEsse fen\u00f4meno \u00e9 denominado:\nA efeito Hawthorne.\nB vi\u00e9s de desempenho.\nC vi\u00e9s de atrito.\nD vi\u00e9s de detec\u00e7\u00e3o.\nE regress\u00e3o \u00e0 m\u00e9dia.\n98\nDe acordo com a refer\u00eancia Nardi, A. E.; Silva, A. G.; Quevedo, J. (org.). Tratado de Psiquiatria da\nAssocia\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022, h\u00e1 um fen\u00f4meno estat\u00edstico capaz de\nfazer com que uma varia\u00e7\u00e3o natural em dados repetidos pare\u00e7a uma mudan\u00e7a real produzida por uma\ninterven\u00e7\u00e3o. Em uma situa\u00e7\u00e3o hipot\u00e9tica na qual a gravidade dos sintomas depressivos de uma\npaciente \u00e9 avaliada imediatamente antes do in\u00edcio do tratamento e, nas duas avalia\u00e7\u00f5es subsequentes,\nobserva-se uma queda na intensidade dos sintomas, pode parecer que o medicamento foi respons\u00e1vel\npela melhora. No entanto, se fosse poss\u00edvel conhecer o curso natural dos sintomas dessa paciente,\nseria plaus\u00edvel que a interven\u00e7\u00e3o medicamentosa n\u00e3o tivesse exercido qualquer efeito. Os sintomas\napresentam um padr\u00e3o natural de oscila\u00e7\u00f5es, com altos e baixos em torno de um ponto central. Como\n\u00e9 comum que o paciente busque ajuda psiqui\u00e1trica justamente quando os sintomas atingem maior\nintensidade, ap\u00f3s certo tempo esses sintomas tendem a retornar ao ponto m\u00e9dio, produzindo uma\nfalsa impress\u00e3o de efic\u00e1cia terap\u00eautica. Esse \u00e9 um dos principais problemas de estudos experimentais\nque utilizam compara\u00e7\u00f5es \u201cantes e depois\u201d.\nEsse fen\u00f4meno \u00e9 denominado:\nA efeito Hawthorne.\nB vi\u00e9s de desempenho.\nC vi\u00e9s de atrito.\nD vi\u00e9s de detec\u00e7\u00e3o.\nE regress\u00e3o \u00e0 m\u00e9dia.\nP\u00e1gina 177\nAlternativa correta: E \u2014 Regress\u00e3o \u00e0 m\u00e9dia.\nResumo objetivo\nO fen\u00f4meno descrito \u2014 melhora aparente ap\u00f3s uma interven\u00e7\u00e3o apenas porque a\nmedi\u00e7\u00e3o inicial ocorreu em um ponto de extrema gravidade, seguido de retorno natural\ndos sintomas ao seu valor habitual \u2014 corresponde exatamente \u00e0 regress\u00e3o \u00e0 m\u00e9dia.\nEsse efeito \u00e9 um problema cl\u00e1ssico dos estudos \u201cantes e depois\u201d, pois cria falsa\nimpress\u00e3o de efic\u00e1cia quando n\u00e3o h\u00e1 grupo controle.\n99\nDe acordo com a refer\u00eancia Nardi, A. E.; Silva, A. G.; Quevedo, J. (org.). Tratado de\nPsiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022, em rela\u00e7\u00e3o\nao tratamento, ainda n\u00e3o foram identificados genes associados \u00e0 farmacodin\u00e2mica e ao\nefeito cl\u00ednico dos antidepressivos. Algumas diretrizes apresentam recomenda\u00e7\u00f5es de\nprescri\u00e7\u00e3o baseadas em polimorfismos de dois genes relacionados \u00e0 metaboliza\u00e7\u00e3o\n(farmacocin\u00e9tica) de determinados medicamentos. Embora essas informa\u00e7\u00f5es gen\u00e9ticas\npossam complementar a avalia\u00e7\u00e3o cl\u00ednica, elas explicam apenas uma pequena fra\u00e7\u00e3o das\ndiferen\u00e7as interpessoais na resposta antidepressiva decorrentes de varia\u00e7\u00f5es no\nmetabolismo.\nAssinale esses dois genes:\nA 2C9 e 3A4.\nB 1A2 e 2B6.\nC TPH1 e TPH2.\nD SLC6A4 e DRD1.\nE 2D6 e 2C19.\n99\nDe acordo com a refer\u00eancia Nardi, A. E.; Silva, A. G.; Quevedo, J. (org.). Tratado de\nPsiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022, em rela\u00e7\u00e3o\nao tratamento, ainda n\u00e3o foram identificados genes associados \u00e0 farmacodin\u00e2mica e ao\nefeito cl\u00ednico dos antidepressivos. Algumas diretrizes apresentam recomenda\u00e7\u00f5es de\nprescri\u00e7\u00e3o baseadas em polimorfismos de dois genes relacionados \u00e0 metaboliza\u00e7\u00e3o\n(farmacocin\u00e9tica) de determinados medicamentos. Embora essas informa\u00e7\u00f5es gen\u00e9ticas\npossam complementar a avalia\u00e7\u00e3o cl\u00ednica, elas explicam apenas uma pequena fra\u00e7\u00e3o das\ndiferen\u00e7as interpessoais na resposta antidepressiva decorrentes de varia\u00e7\u00f5es no\nmetabolismo.\nAssinale esses dois genes:\nA 2C9 e 3A4.\nB 1A2 e 2B6.\nC TPH1 e TPH2.\nD SLC6A4 e DRD1.\nE 2D6 e 2C19.\nP\u00e1gina 708\nAlternativa correta: E \u2014 2D6 e 2C19\nExplica\u00e7\u00e3o objetiva\nAs diretrizes internacionais de farmacogen\u00e9tica (como CPIC e DPWG) utilizam\npolimorfismos nos genes CYP2D6 e CYP2C19 para orientar ajustes de dose de\ndiversos antidepressivos (ISRSs e IRSNs principalmente).\nEsses genes influenciam metaboliza\u00e7\u00e3o (farmacocin\u00e9tica), n\u00e3o o efeito\nfarmacodin\u00e2mico.\nPor isso, E \u00e9 a resposta correta.\n100\nDe acordo com a refer\u00eancia Nardi, A. E.; Silva, A. G.; Quevedo, J. (org.). Tratado de\nPsiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022, em\n1892, Arnold Pick descreveu o primeiro caso de degenera\u00e7\u00e3o lobar frontotemporal\n(DLFT), caracterizado por afasia, atrofia lobar e dem\u00eancia pr\u00e9-senil. Em 1907, Alois\nAlzheimer identificou a associa\u00e7\u00e3o entre os corp\u00fasculos de Pick e o quadro cl\u00ednico\nobservado, denominando a condi\u00e7\u00e3o como doen\u00e7a de Pick. Apesar do longo per\u00edodo de\nestudos sobre DLFT, apenas em 1982 Marek M. Mesulam descreveu um subtipo de\nDLFT marcado por comprometimento predominante da linguagem, posteriormente\ndefinido como:\nA s\u00edndrome corticobasal.\nB variante comportamental da DLFT.\nC paralisia supranuclear progressiva.\nD afasia progressiva prim\u00e1ria.\nE subtipo desinibido da DLFT.\n100\nDe acordo com a refer\u00eancia Nardi, A. E.; Silva, A. G.; Quevedo, J. (org.). Tratado de\nPsiquiatria da Associa\u00e7\u00e3o Brasileira de Psiquiatria. Porto Alegre: Artmed, 2022, em\n1892, Arnold Pick descreveu o primeiro caso de degenera\u00e7\u00e3o lobar frontotemporal\n(DLFT), caracterizado por afasia, atrofia lobar e dem\u00eancia pr\u00e9-senil. Em 1907, Alois\nAlzheimer identificou a associa\u00e7\u00e3o entre os corp\u00fasculos de Pick e o quadro cl\u00ednico\nobservado, denominando a condi\u00e7\u00e3o como doen\u00e7a de Pick. Apesar do longo per\u00edodo de\nestudos sobre DLFT, apenas em 1982 Marek M. Mesulam descreveu um subtipo de\nDLFT marcado por comprometimento predominante da linguagem, posteriormente\ndefinido como:\nA s\u00edndrome corticobasal.\nB variante comportamental da DLFT.\nC paralisia supranuclear progressiva.\nD afasia progressiva prim\u00e1ria.\nE subtipo desinibido da DLFT.\nP\u00e1gina 1264\nAlternativa correta: D \u2014 Afasia progressiva prim\u00e1ria\nExplica\u00e7\u00e3o objetiva\nEm 1982, Marek Mesulam descreveu um quadro cl\u00ednico caracterizado por decl\u00ednio\nprogressivo da linguagem, preservando inicialmente outras fun\u00e7\u00f5es cognitivas.\nEsse quadro foi posteriormente denominado Afasia Progressiva Prim\u00e1ria (APP), hoje\nreconhecida como um dos subtipos de degenera\u00e7\u00e3o lobar frontotemporal (DLFT).\nPor isso, a alternativa correta \u00e9 D.",
        },
        correctAnswer: 'D',
        comment: "\u2014 Afasia progressiva prim\u00e1ria\nExplica\u00e7\u00e3o objetiva\nEm 1982, Marek Mesulam descreveu um quadro cl\u00ednico caracterizado por decl\u00ednio\nprogressivo da linguagem, preservando inicialmente outras fun\u00e7\u00f5es cognitivas.\nEsse quadro foi posteriormente denominado Afasia Progressiva Prim\u00e1ria (APP), hoje\nreconhecida como um dos subtipos de degenera\u00e7\u00e3o lobar frontotemporal (DLFT).\nPor isso, a alternativa correta \u00e9 D.",
    },
];
